openshift-kni/oran-o2ims

Containerfile, Makefile, README.md
Now that the project has been moved to the `openshift-kni/oran-o2ims` GitHub repository the _Makefile_ and _Containerfile_ need to be updated to use the new `oran-o2ims` binary generated by default.
Related: https://issues.redhat.com/browse/MGMT-16110
=> Adjust Makefile and Container file for new home

.vscode/launch.json, go.mod, go.sum, internal/cmd/server/flags.go, internal/cmd/server/start_deployment_manager_server.go, internal/cmd/server/start_metadata_server.go, internal/service/cloud_info_handler.go, internal/service/object_adapter.go, internal/service/versions_handler.go
This patch adds a new `metadata-server` that responds to the API versions and cloud information endpoints. For example, for the API versions:
```shell
$ curl http://localhost:8080/O2ims_infrastructureInventory/api_versions
{
"uriPrefix": "/O2ims_infrastructureInventory/v1",
"apiVersions": [
{
"version": "1.0.0"
}
]
}
$ curl http://localhost:8080/O2ims_infrastructureInventory/v1/api_versions
{
"uriPrefix": "/O2ims_infrastructureInventory/v1",
"apiVersions": [
{
"version": "1.0.0"
}
]
}
```
And for the cloud information:
```shell
$ curl http://localhost:8080/O2ims_infrastructureInventory/v1
{
"oCloudId": "6575154c-72fc-4ed8-9a87-a81885ab38bb",
"globalCloudId": "6575154c-72fc-4ed8-9a87-a81885ab38bb",
"name": "OpenShift O-Cloud",
"description": "OpenShift O-Cloud",
"serviceUri": …
```
=> Add metadata server

.gitignore, proxy.sh, proxy.yaml
This patch adds a `proxy.sh` script that starts the servers and the reverse proxy in the local machine. The reverse proxy is Envoy, and the configuration is in the `proxy.yaml` file.
To use it run the `run.sh` script. It will start the metadata server listening in port 8000, the deployment manager server listening in port 80001 and the reverse proxy listening in port 9000. Then, for example, go to port 9000 to get the list API versions served by the metadata server:
http://localhost:9000/O2ims_infrastructureInventory/api_versions
Or to get the the list of deployment managers server by the deployment manager server:
http://localhost:9000/O2ims_infrastructureInventory/v1/deploymentManagers
To finish, type Ctrl+C and the proxy and the servers will be killed.
The administration port of the …
=> Add development reverse proxy

internal/searchapi/generate.go, internal/searchapi/searchapi.go
We copy the GraphQL models from the `stolostron/search-api-v2` project in order to avoid additional dependencies. This patch adds `go:generate` directives to automatically update that code when `make generate` is executed.
Related: https://issues.redhat.com/browse/MGMT-16108
Related: https://github.com/stolostron/search-v2-api/blob/main/graph/schema.graphqls
Related: https://github.com/stolostron/search-v2-api/blob/main/graph/model/models_gen.go
=> Automatically update and check copied code

Containerfile.tools
This is required by the ci-operator in openshift/release.
=> Update Containerfile.tools to install git

go.mod, go.sum, internal/service/deployment_manager_handler.go
This patch changes the code that translates managed clusters into deployment managers. To do so it uses a set of jq queries that are compiled only once and executed in an almost declarative way.
=> Simplify deployment manager field mapping

go.mod, go.sum, internal/service/resource_pool_fetcher.go, internal/service/resource_pool_handler_test.go
Set 'location' in ResourcePool object according to a 'region' label in the cluster (if exists).
=> MGMT-16243: set 'location' property on ResourcePool

internal/search/projector_evaluator.go, internal/search/projector_evaluator_test.go, internal/search/selector_evaluator.go
Currently when a projector contains multiple nested fields an extra field will be added with the name of the container. For example, if the projector contains `a/b,a/c` the result will be:
```
{
"a" : {
"b": "B"
"c": "C",
"a": "C"
}
}
```
Note the extra `a.a` field, with value `C`. That shouldn't be there, it is an artifact of the projector evaluator. This patch fixes that issue.
=> Fix projection with multiple fields

internal/cmd/server/flags.go, internal/cmd/server/start_deployment_manager_server.go, internal/jq/tool.go, internal/service/deployment_manager_handler.go, internal/service/deployment_manager_handler_test.go
Currently the population of the _extensions_ field is completely hardcoded. This patch adds support for populating it in a configurable way. A new `--extensions` command line option is added to the deployment manager server. The value will be a jq script that calculates extension fields. For example, if the managed cluster has a `country` label the following command line option will configure the server to add a corresponding `country` extension:
```
--extensions={
"country": .metadata.labels["country"]
}
```
For a cluster where the value of the `contry` label is `ES` that will result in the following extensions:
```json
{
"country": "ES"
}
```
Related: https://issues.redhat.com/browse/MGMT-16351
=> MGMT-16351: Add support for configured extensions

internal/search/path.go, internal/search/path_evaluator.go, internal/search/paths_lexer.go, internal/search/paths_parser.go, internal/search/paths_parser_test.go, internal/search/projector.go, internal/search/projector_evaluator.go, internal/search/projector_evaluator_test.go, internal/search/projector_parser.go, internal/search/projector_parser_test.go, internal/search/projector_test.go, internal/search/selector_evaluator.go, internal/search/selector_evaluator_test.go, internal/service/collection_adapter.go, internal/service/collection_adapter_test.go, internal/service/collection_handler.go, internal/service/object_adapter.go, internal/service/object_adapter_test.go, internal/service/object_handler.go
This patch adds support for the `exclude_fields` query parameter as defined in section 5.3.2 of the ETSI GS NFV-SOL 013 document. For, example, to exclude the _name_ field from the list of deployment managers:
```
GET /o2ims-infrastructureInventory/v1/deploymentManagers?exclude_fields=name
```
This requires a large refactoring of the search package, as well as changes in the adapters. The logic handlers aren't affected.
Related: https://issues.redhat.com/browse/MGMT-16391
Related: https://www.etsi.org/deliver/etsi_gs/NFV-SOL/001_099/013/03.03.01_60/gs_NFV-SOL013v030301p.pdf
=> MGMT-16391: Add support for `exclude_fields`

go.mod, internal/graphql/graphql.go, internal/graphql/graphql_test.go, internal/graphql/suite_test.go, internal/service/resource_fetcher.go, internal/service/resource_handler.go, internal/service/resource_handler_test.go, internal/service/resource_pool_fetcher.go, internal/service/resource_pool_handler.go, internal/service/resource_pool_handler_test.go, internal/service/resource_type_handler.go
Optimized the filtering of search results in the resource server. I.e. instead of filtering the items after fetching a response, used the filter functionality of [GraphQL](https://github.com/stolostron/search-v2-operator/wiki/Search-Query-API#sample-queries) search query API. This change includes the required mapping from 'filter' query param (as defined in the NFV spec) into SearchFilter as used in GraphQL.
Note: for any unsupported search operator by GraphQL, we fallback to the regular selector filtering.
=> MGMT-16307: Optimize GraphQL search using filters

Makefile, go.mod, hack/install_test_deps.sh, internal/cmd/server/start_metadata_server.go, internal/openapi/handler.go, internal/openapi/handler_test.go, internal/openapi/lint.yaml, internal/openapi/spec.yaml, internal/openapi/suite_test.go
This patch adds a new `/o2ims-infrastructureInventory/v1/openapi` endpoint that returns the OpenAPI specification of the service.
Currently this specification only covers the metadata and the deployment manager endpoints. Other endpoints will be added later.
Related: https://issues.redhat.com/browse/MGMT-16112
=> MGMT-16112: Add OpenAPI handler

.github/workflows/check-pull-request.yaml, Makefile, internal/openapi/handler_test.go
Currently there is a `lint-openapi` tarket in the Makefile that runs the 'spectral' tool to check the OpenAPI specification. This patch moves that to the unit tests, so that there will be no need to run a separate command.
Related: https://issues.redhat.com/browse/MGMT-16112
=> MGMT-16112: Run 'spectral' checks in unit tests

internal/cmd/server/start_resource_server.go, internal/service/adapter.go
* Added "resourceID" to SetPathVariables in order to support '/resourcePools/{resourcePoolID}/resources' endpoint.
* Note: the ['Unify collection and object adapters'](https://github.com/openshift-kni/oran-o2ims/pull/44) change relies on it.
* Added missing handling to a 'not found' object in serveObject func.
* Identifying a stream end error.
=> Fix resources endpoint collection

internal/cmd/server/start_deployment_manager_server.go, internal/service/deployment_manager_handler.go, internal/service/deployment_manager_handler_test.go
Currently the deployment manager server expects to have an ACM global hub as the backend. This patch adds support for using a regular ACM hub. The new `--backend-type=global-hub|regular-hub` command line flag will be used to select the type of hub. When using a global hub the deployment manager server will use the non-kubernetes API of the hub. When using a regular hub it will use the `ManagedCluster` Kubernetes API.
=> Add support for regular hub

internal/graphql/graphql.go, internal/graphql/graphql_test.go
Handling unknown GraphQL filter property in MapFilter func.
It is required to fallback into selector filtering when the specified property is not available in the search response.
E.g. ?filter=(eq,location,US) --> should filter using the selector.
=> graphql: handle unknown property in MapFilter

.vscode/launch.json, internal/cmd/server/flags.go, internal/cmd/server/start_metadata_server.go, internal/controllers/orano2ims_controller.go, internal/service/cloud_info_handler.go
This patch adds a new `--externa-address` option to the metadata server. It is used to populate the `serviceUri` field returned by the `/o2ims-infrastructureInventory/v1` endpoint. The operator calculates this using the host name of the ingress.
=> Add `--external-address` to metadata server

docs/dev/env_devscripts.md, docs/dev/env_kcli.md
Added a documentation for deploying a development environment using dev-scripts. This is mandatory for using the Observability service which requires a DNS config that allows the Hub cluster to be reachable from the spokes.
=> MGMT-16856: observability env using dev-scripts

.gitignore
The `controller-gen` and `manager` binaries were accidentally added to the repository. This patch removes them.
=> Remove tool binaries from the repository

internal/service/adapter.go, internal/service/adapter_test.go, internal/service/handlers.go, internal/service/handlers_mock.go
This patch adds support for the `POST` HTTP method. The adapter will now accept the `POST` method and call the `Add` method defined in the `AddHandler` interface. An implementation of this interface will receive the request body already parsed, and should add the object to the collection and return it. For example, a simple implementation that stores the object in a map in memory could look like this:
```go
func (h *MyHandler) Add(ctx context.Context, request *AddRequest) (respone *AddResponse, err error) {
h.storeLock.Lock()
defer h.storeLock.Unlock()
h.storeMap[request.Variables[0]] = request.Object
response := &AddResponse{
Object: request.Object,
}
return
}
```
In order to make naming of the interfaces more consistent this patch also renames `ObjectHandler` to `GetHandler` and …
=> Add POST support

internal/service/adapter.go, internal/service/adapter_test.go, internal/service/handlers.go, internal/service/handlers_mock.go
Add DELETE support
This patch adds support for the `DELETE` HTTP method. The adapter will now accept the `DELETE` method and call the `Delete` method defined in the `DeleteHandler` interface. For example, a simple implementation that stores the object in a map in memory could look like this:
```go
func (h *MyHandler) Delete(ctx context.Context, request *AddRequest) (respone *AddResponse, err error) {
h.storeLock.Lock()
defer h.storeLock.Unlock()
delete(h.storeMap, request.Variables[0])
return
}
```
=> Add DELETE support

.vscode/launch.json, internal/cmd/server/start_alarm_server.go, internal/cmd/start_cmd.go, internal/k8s/stream.go, internal/service/alarm_fetcher.go, internal/service/alarm_handler.go
Added the basic components for the Alarm server:
* AlarmServer cobra command
* AlarmHandler service (handles List/Get requests)
* AlarmFetcher (invoke the requests to the Alertmanager)
This PR mainly includes the boilerplate needed for the server basic functionality.
For now, the server simply returns the list of alert objects from Alertmanager API as-as.
The consecutive PRs will include the actual mapping to O-Cloud objects.
=> MGMT-16974: Introducing the Alarm server

docs/dev/env_devscripts.md
Replace hardcoded "git" user on dev-script's path with a variable $USER.
Typo swapped a comma with period.
=> Clarify the need to clone assited repo on spoke deployment step.

api/v1alpha1/orano2ims_types.go, config/crd/bases/oran.openshift.io_orano2imses.yaml, config/manager/kustomization.yaml, internal/cmd/server/start_deployment_manager_server.go, internal/controllers/orano2ims_controller.go, internal/controllers/utils/constants.go, internal/controllers/utils/utils.go, internal/controllers/utils/utils_test.go
Currently the backend URL and token don't have defaults. That means that the user has to explicitly set them in the custom resource that represents the O2 IMS deployment. That is reasonable for the URL, but not for the token, because it is the token of a service account that is created by the operator. That means that the user would have to create the service account in advance, wait for the token to be created and then read it and update the custom resource. That isn't practical. To avoid that this patch changes the operator so that the token is the default URL of the Kubernetes API server and the token is taken from the `/run/secrets/kubernetes.io/serviceaccount/token` file.
=> Add defaults for deployment manager backend URL and token

Containerfile
Currently when we build the container image we put the source code in the home directory of the `builder` user. That means that the source code will be in `/home/builder` and the Go module cache will be in `/home/builder/go/pkg`. A side effect of that is that tools like `controller-gen` that scan directories looking for Go code will find our source code, but also the source code of the modules in that module cache. That results in errors because the tool will not find the dependencies of those incorrect source files. To avoid that this patch changes the `Containerfile` so that the source code will be in `/home/builder/project` and the Go module cache in `/home/builder/go/pkg`, that way `controller-gen` will run inside `/home/builder/project` and will not find the Go module cache source …
=> Don't put Go directory at the same level than source

internal/service/deployment_manager_handler.go
Currently the deployment manager service uses the admin kubeconfig that was used to register the cluster with ACM. But this will not exist if the cluster was created with assisted installer. To avoid that problem this patch changes the service so that it first check if the secret used by the assisted installer exists. If it does exist then it will use it.
=> Use assisted installer admin kubeconfig if exists

internal/cmd/server/start_deployment_manager_server.go
When the `--backend-token-file` was introduced the `--backend-token` should have been made optional, but it wasn't. This patch fixes that.
=> Make deployment manager server `--backend-token` optional

internal/controllers/orano2ims_controller.go, internal/controllers/utils/utils.go, internal/controllers/utils/utils_test.go
Currently this function has nine parameters. Two of them are the name and namespace of the object, but the object itself is also passed. Assuming that the `Name` and `Namespace` fields of the object will be populated it is not necessary to have additional parameters for that. This patch removes those parameters.
=> Reduce numer of parameters of `CreateK8sCR`

internal/controllers/orano2ims_controller.go, internal/controllers/utils/utils.go, internal/controllers/utils/utils_test.go
Currently the `CreateK8sCR` function receives an `oldObject` parameter that is needed because the function doesn't know how to create an empty object of the same type of the object that is going to be created. But that can be solved using reflection, something like this:
```go
// Create an empty object of the same type of the new object. We will use it to
// fetch the current state.
objectType := reflect.TypeOf(newObject).Elem()
oldObject := reflect.New(objectType).Interface().(client.Object)
```
This patch does that and removes the `oldObject` parameter, which simplifies the code that calls the `CreateK8sCR` function.
=> Remove `oldObject` parameter from `CreateK8sCR`

internal/controllers/utils/utils.go
Kubernetes forbids the creation of object in one namespace with owners in another namespace, or the creation of non-namespaced objects with namespaced owners. But the `CreateK8sCR` function doesn't support. We will need that in order to create cluster roles and cluster role bindings. This patch changes the function so that it will not try to set an owner if the namespace of the object and the namespace of the owner are different.
=> Support creation of non namespaced objects in createk8scr

Makefile, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, bundle/manifests/oran.openshift.io_orano2imses.yaml, config/manager/kustomization.yaml, config/manifests/bases/oran-o2ims.clusterserviceversion.yaml, config/rbac/role.yaml, internal/controllers/orano2ims_controller.go
The service account that is used to run the deployment manager server needs permissions to read `ManagedCluster` objects and assisted installer admin kubeconfig secrets. This patch changes the operator so that it creates the corresponding cluster roles and cluster role bindings. In order to do so the operator needs to also have those permissions, as Kubernetes forbids granting more permissions than the service account granting them already has. So this patch also adds those permissions to the service account that is used to run the operator.
=> Grant deployment manager server account permissions to read managed clusters and secrets

cmd/main.go, internal/controllers/orano2ims_controller.go, internal/controllers/orano2ims_controller_test.go, internal/controllers/utils/utils.go, internal/controllers/utils/utils_test.go
It isn't necessary to explicitly pass the scheme paratemer to the `CreateK8sCR` function because it can obtain it calling the `Scheme()` function of the client.
=> Remove scheme parameter of `CreateK8sCR` and `ORANO2IMSReconciler`

cmd/main.go, internal/controllers/orano2ims_controller.go, internal/controllers/orano2ims_controller_test.go
This patch adds a new `reconcilerTask` that contains the logic and data needed to perform the reconciliation process. It contains, for example, the state of the object being reconciled. This reduces the number of parameters that need to be passed to methods, as some of them are available as fields of the receiver.
=> Add reconciler task

internal/cmd/operator/start_controller_manager.go, internal/controllers/orano2ims_controller.go, internal/controllers/orano2ims_controller_test.go, internal/controllers/suite_test.go
Currently we use the `slog` logging library in the servers and the `logr` library in the controllers. To make things a bit more consistent this patch changes the controllers to use `slog`.
=> Use slog in controllers

Containerfile, Dockerfile, api/v1alpha1/orano2ims_types.go, config/crd/bases/oran.openshift.io_orano2imses.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, internal/cmd/operator/start_controller_manager.go, internal/controllers/orano2ims_controller.go, internal/controllers/utils/constants.go
Currently the container image used by the servers is hardcoded in the Go source code. This complicates development because when the operator is deployed it isn't possible to use a custom image. To simplify that this patch adds a new `--image` command line flag to the `start controller-manager` command. The default will be
`quay.io/openshift-kni/oran-o2ims:latest`, but it will be possible to change it in the the development environment, in two different ways:
1. Changing the `IMG` make variable, for example:
```
$ make IMG=quay.io/myuser/myimage:123 build deploy
```
2. Using the `spec.image` field of the custom resource.
The patch also changes The kustomization files used to generate tha operator manifests so that the selected image is automatically passed to the `--image` command line …
=> Make image configurable

internal/authentication/handler_wrapper.go, internal/authorization/handler_wrapper.go, internal/cmd/operator/start_controller_manager.go, internal/cmd/server/start_alarm_server.go, internal/cmd/server/start_alarm_subscription_server.go, internal/cmd/server/start_deployment_manager_server.go, internal/cmd/server/start_metadata_server.go, internal/cmd/server/start_resource_server.go, internal/cmd/version_cmd.go, internal/controllers/orano2ims_controller.go, internal/k8s/stream.go, internal/logging/transport_wrapper.go, internal/openapi/handler.go, internal/search/projector_evaluator.go, internal/search/selector_evaluator.go, internal/service/adapter.go, internal/service/alarm_definition_handler.go, internal/service/alarm_fetcher.go, internal/service/alarm_subscription_handler.go, internal/service/deployment_manager_handler.go, internal/service/resource_fetcher.go, internal/service/resource_handler.go, internal/service/resource_pool_fetcher.go, internal/service/resource_pool_handler.go, internal/service/resource_type_handler.go, internal/service/versions_handler.go, internal/tool.go
Currently whe use the `Info`, `Error` and `Debug` methods of the `slog.Logger` package, which don't receive a context. There are `InfoContext`, `ErrorContext` and `DebugContext` that receive a context as a parameter and make it possible to later include context information in the generated log messages. This patch changes our code to use those variants, so that we will eventually be able to use that context information.
=> Use logging context where possible

Makefile, internal/cmd/server/start_alarm_server.go, internal/cmd/server/start_alarm_subscription_server.go, internal/cmd/server/start_deployment_manager_server.go, internal/cmd/server/start_metadata_server.go, internal/cmd/server/start_resource_server.go, internal/exit/handler.go, internal/metrics/handler_wrapper.go, internal/metrics/handler_wrapper_test.go, internal/metrics/labels.go, internal/metrics/path_tree.go, internal/metrics/path_tree_test.go, internal/metrics/suite_test.go, internal/metrics/transport_wrapper.go, internal/metrics/transport_wrapper_test.go, internal/network/listener.go, internal/testing/metrics.go
This patch adds to all the servers a metrics server that provides the default metrics generated by the Prometheus Go instrumentation library as well as metrics for the number of duration of inbound HTTP requests.
The metrics handler will listen by default in port 8001, but that can be changed with the following options:
- `--metrics-listener-address` - Metrics listen address. (default "localhost:8001")
- `--metrics-listener-tls-crt` - Metrics TLS certificate in PEM format.
- `--metrics-listener-tls-key` - Metrics TLS key in PEM format.
The metrics generated are the following:
- `inbound_request_count` - Number of API requests sent.
- `inbound_inbound_request_duration_sum` - Total time to send API requests, in seconds.
- `inbound_inbound_request_duration_count` - Total number of API …
=> Add metrics for inbound HTTP requests

internal/cmd/server/start_alarm_subscription_server.go, internal/k8s/client.go, internal/persiststorage/persiststorage.go, internal/persiststorage/persiststorage_configmap.go, internal/service/alarm_subscription_handler.go, internal/service/alarm_subscription_handler_test.go, proxy.sh
This is WIP version for alarm subscription server using configmap for now.
=> Subscription server use ConfigMap as persistent storage as well as IPC

internal/tool.go
Currently the name of the binary is `oran-o2ims` but the output of the `--help` option says `o2ims`. This patch fixes that.
Related: https://github.com/openshift-kni/oran-o2ims/issues/104
=> Fix binay name in help output

Makefile, config/crd/bases/hardwaremanagement.oran.openshift.io_nodeallocationrequests.yaml, config/crd/bases/hardwaremanagement.oran.openshift.io_nodereleaserequests.yaml, config/crd/bases/oran.openshift.io_deploymentmanagerorders.yaml, config/crd/bases/oran.openshift.io_deploymentmanagers.yaml, config/crd/bases/oran.openshift.io_deploymentmanagertemplates.yaml, config/crd/bases/oran.openshift.io_orano2imses.yaml
Version of `controller-gen` 0.13.0 crashes like this when we execute `make install`:
```
/home/user/repos/oran-o2ims/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0de0f]goroutine 1 [running]:
go/types.(*Checker).handleBailout(0xc0004aa600, 0xc000e42a18)
/usr/lib/golang/src/go/types/check.go:367 +0x88
panic({0xbc7860?, 0x12b48a0?})
/usr/lib/golang/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xdc35b8, 0x12bd080})
/usr/lib/golang/src/go/types/sizes.go:228 +0x30f …
```
=> MGMT-18232: Avoid `controller-gen` crash

internal/service/adapter.go, internal/service/adapter_test.go, internal/service/alarm_handler.go, internal/service/deployment_manager_handler.go, internal/service/resource_handler.go, internal/service/resource_pool_handler.go, internal/service/resource_type_handler.go, internal/service/subscription_handler.go
Currently we apply the selector (the `filter` query parameter) in all the handlers. This patch moves the logic to the adapter, which is where it belongs.
=> NO-ISSUE: Move selector logic from handlers to adapter

internal/files/controllers/siteconfig-template-cm.yaml
- follows the required/optional fields defined in the [siteconfig API](https://github.com/stolostron/siteconfig/blob/main/api/v1alpha1/siteconfig_types.go)
- toYaml is a custom template function being used to convert complex nested structures into YAML format string within the template, without the need to specify each field from a map or iteraging over each element of a list. This is helpful for an optional field without required nested fields
- indent is a srig function that adds a specified number of spaces before each line of the output. This is used with toYaml function to ensure the corrent indention of YAML string
- The default values will be provided in another configmap and be merged with the configuration provided in the ClusterRequest.ClusterTemplateInput field. The merged data …
=> initial commit for siteconfig template cm

README.md, internal/cmd/server/start_alarm_server.go
Fixed some typos related to Alarms/Alertmanager.
=> NO-ISSUE: fix typos related to alarms

.vscode/launch.json, README.md, internal/cmd/server/flags.go, internal/cmd/server/start_alarm_notification_server.go, internal/cmd/server/start_alarm_server.go, internal/cmd/server/start_infrastructure_inventory_subscription_server.go, internal/cmd/start_cmd.go, internal/controllers/utils/constants.go, internal/persiststorage/persiststorage.go, internal/persiststorage/persiststorage_configmap.go, internal/service/alarm_fetcher.go, internal/service/alarm_mapper.go, internal/service/alarm_notification_dispatcher.go, internal/service/alarm_notification_handler.go, internal/service/alarm_notification_handler_test.go, internal/service/alarm_notification_searcher.go, internal/service/constants.go, internal/service/subscription_handler.go, internal/service/subscription_handler_test.go, proxy.sh
Create the alarm notification server.
Manage in memory alarm subscriptions base on persist storage (populated by alarm subscription server).
Prebuilt subscription filter terms + limited optimization
Accept the alarms, match the filters and build and send out notification packet based on matched subscription.
This PR supports basic alert packet flow. In future the filter match will have more optimization and the alert to notification the attributes may need fine tuned.
=> Supports for alarm notification server:

internal/authentication/handler_wrapper.go, internal/service/alarm_fetcher.go, internal/service/alarm_handler.go, internal/service/deployment_manager_handler.go, internal/service/resource_fetcher.go, internal/service/resource_handler.go, internal/service/resource_pool_fetcher.go, internal/service/resource_pool_handler.go, internal/service/resource_type_handler.go
The zero value of HttpTransport doesn't include any default attribute values for setting up the HTTP transport.  This prevents using the HTTPS_PROXY environment variable (and other related proxy variables) to redirect HTTP requests to a proxy.
We could set this explicitly on our own, but that wouldn't pick up any future changes to the defaults made upstream in the library.
This is useful when testing as a standalone binary and connecting to a system that is behind a proxy.
=> Set transport defaults when creating HTTP backend transport

Makefile
Now that the `vendor` directory is no longer excluded from git we need to adjust the `gofmt` input parameters to exclude it since it currently looks at any and all *.go files within the entire repo.  This causes it to run on files within the vendor directory which, as it turns out, contains some *.go files that do not conform to the go formatting guidelines.
Alternatively we could have explicitly listed the required source directories, but figured that this dynamic approach would be more "future-proof" and require less code maintenance.
=> Exclude vendor directory from gofmt input parameters

.golangci.yml, internal/authentication/handler_wrapper.go, internal/service/alarm_fetcher.go, internal/service/alarm_handler.go, internal/service/deployment_manager_handler.go, internal/service/resource_fetcher.go, internal/service/resource_handler.go, internal/service/resource_pool_fetcher.go, internal/service/resource_pool_handler.go, internal/service/resource_type_handler.go
This addresses import statement ordering/grouping violations reported by the golintci tool.
=> CNF-13957: Enable goimports linter configuration

.golangci.yml, internal/jq/query.go
This addresses issues with unnecessary type conversions reported by the golintci tool.
=> CNF-13961: Enable unconvert linter configuration

.golangci.yml, internal/authentication/handler_wrapper.go, internal/authorization/handler_wrapper.go, internal/controllers/clusterrequest_controller.go, internal/k8s/client.go, internal/logging/logger.go, internal/search/projector_evaluator.go, internal/service/adapter.go, internal/service/alarm_notification_searcher.go, internal/service/deployment_manager_handler.go, internal/service/resource_handler.go, internal/service/resource_pool_handler.go, internal/service/subscription_handler.go
Enabling golangci-lint unparam test. For most existing issues, the test is skipped via `nolint: unparam` directive, as the code is under development and unused parameters are likely to be used in the future.
In one case (internal/authentication/handler_wrapper.go), the warning flagged a function that always returned nil error, which is addressed by returning a wrapped error in the failure case.
=> CNF-13962: Enable golangci-lint unparam test

.golangci.yml, internal/authentication/handler_wrapper.go, internal/logging/transport_wrapper.go, internal/metrics/handler_wrapper.go, internal/metrics/transport_wrapper.go, main.go
This addresses issues with improperly unwrapped error objects reported by the golintci tool.
=> CNF-13953: Enable errorlint linter configuration

.golangci.yml, internal/search/projector_evaluator_test.go, internal/search/selector_evaluator_test.go, internal/service/alarm_notification_searcher.go
The following golangci-lint linters are enabled:
- errcheck
- gosimple
- importas
- nilnil
- predeclared
- promlinter
- sloglint
- usestdlibvars
=> CNF-13952: Enable additional golangci-lint linters

internal/controllers/clusterrequest_controller.go, internal/controllers/clusterrequest_controller_test.go, internal/controllers/utils/constants.go, internal/controllers/utils/utils.go, internal/controllers/utils/utils_test.go
Description:
- update the policy template configMap keys to keep them the same as the default policy template configMap
- do not check for a policy label on the clusterInstance (the user needs to make sure the labels used in the ClusterInstance and the ACM PGs match)
- add unit tests
=> CNF-13707: Policy template configMap updates

Dockerfile
By separating the vendor folder to its own COPY directive in the Dockerfile, the build is able to make use of the cached directory more efficiently, as the vendor files will change infrequently.
=> NO-ISSUE: Update Dockerfile to copy vendor folder as separate layer

.golangci.yml, internal/authentication/handler_wrapper.go, internal/authorization/handler_wrapper.go, internal/cmd/server/start_alarm_notification_server.go, internal/cmd/server/start_alarm_server.go, internal/cmd/server/start_alarm_subscription_server.go, internal/cmd/server/start_deployment_manager_server.go, internal/cmd/server/start_infrastructure_inventory_subscription_server.go, internal/cmd/server/start_metadata_server.go, internal/cmd/server/start_resource_server.go, internal/controllers/clusterrequest_controller.go, internal/controllers/clustertemplate_controller.go, internal/controllers/clustertemplate_controller_test.go, internal/controllers/orano2ims_controller.go, internal/controllers/utils/utils.go, internal/jq/query.go, internal/jq/tool.go, internal/k8s/client.go, internal/logging/transport_wrapper.go, internal/persiststorage/persiststorage.go, internal/service/alarm_definition_handler.go, internal/service/alarm_probable_cause_handler.go, internal/tool.go
Enables wrapcheck in `.golangci.yml` and fixes issues highlighted by the linter.
/cc @donpenney @alegacy
=> CNF-13963: golangci-lint: Enable wrapcheck in linter configs

api/hardwaremanagement/v1alpha1/node.go, config/crd/bases/hardwaremanagement.oran.openshift.io_nodes.yaml, internal/controllers/clusterrequest_controller.go, vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/node.go
Enhanced the IMS operator to update Node status with the hostname post-BMC assignment, retrieve the bootMacAddress from Node status to update the ClusterInstance, and restructured the code for better maintainability.
=> CNF-14009: Node Hostname Update and BootMacAddress Retrieval

Containerfile.tools
Certain golangci-lint linters require the diff util, which is not installed by default in the ubi-minimal image, which is used for the buildroot image in the CI. This must be a standalone commit as the CI gets the Containerfile.tools file from the branch HEAD, rather than the PR being tested.
=> NO-ISSUE: Add diffutils package to buildroot image

api/hardwaremanagement/v1alpha1/conditions.go, api/hardwaremanagement/v1alpha1/node_pools.go, config/crd/bases/hardwaremanagement.oran.openshift.io_nodepools.yaml, internal/controllers/clusterrequest_controller.go, vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/conditions.go, vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/node_pools.go
Use a single condition type for tracking the NodePool provisioning status, with various condition reasons to represent different states in the provisioning process. This simplifies the condition handling by focusing on one type with multiple reasons for clarity and consistency.
=> Add NodePool Provisioning Status Condition Constants

internal/authentication/handler_wrapper_test.go, internal/controllers/utils/constants.go, internal/controllers/utils/utils.go, internal/service/alarm_fetcher.go, internal/service/alarm_handler.go, internal/service/deployment_manager_handler.go, internal/service/resource_fetcher.go, internal/service/resource_handler.go, internal/service/resource_pool_fetcher.go, internal/service/resource_pool_handler.go, internal/service/resource_type_handler.go, internal/service/suite_test.go
This configures the TLS clients using the service account root CA bundles so that we can properly verify the identity of backend servers.
=> CNF-13958: Enable TLS verification for in-cluster deployments

Dockerfile.tools
This update is to support the change to reduce to one image build in: https://github.com/openshift/release/pull/54191
=> NO-ISSUE: Copy Containerfile.tools to Dockerfile.tools for CI changes

Makefile, bundle.Dockerfile, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, hack/check-git-tree.sh, vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/node.go, vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/node_pools.go
This update includes the following changes:
- Added a git tree check to the ci-job to ensure all changes are included in a PR.
- Update vendor folder with missing changes from earlier PR
- Update Makefile operator-sdk rules to use the downloaded executable, rather than the executable in the user's PATH
=> NO-ISSUE: Add git tree check to ci-job and fix operator-sdk Makefile usage

bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/manifests/bases/oran-o2ims.clusterserviceversion.yaml
Adds annotations to configure the initial upgrade path for the operator.
Signed-off-by: Leonardo Ochoa-Aday <lochoa@redhat.com>
=> CNF-13592: bundle: Add annotations to configure the initial upgrade path

internal/controllers/clusterrequest_controller.go, internal/controllers/clusterrequest_controller_test.go
This change force the clusterrequest object to update the ConfigurationApplied condition to completed only if all the policies are compliant.
TODO:
~System test~
=> Update the ConfigurationApplied condition to completed only if all the policies are compliant

internal/controllers/clusterrequest_controller.go, internal/controllers/clusterrequest_controller_test.go, internal/controllers/utils/conditions.go
Currently, if the condition status is changed, it always be added in the last condition in the list, which causes the confusion. This update will keep the original order of the conditions as they were initially popluated according to a specific logic.
Start handling cluster provisioning only when the hwProvisioned condition is available (also consider provisioning completed when the hardware plugin is ready), and start handling policy configuration only when the clusterProvisioned condition is available.
=> Keep status conditions in order of their original popluation logic

internal/controllers/clusterrequest_controller.go, internal/controllers/clusterrequest_controller_test.go, internal/controllers/utils/utils.go, internal/controllers/utils/utils_test.go
The ClusterInstance template is explicitly defined and delivered within the IMS operator. When new fields are available in the Siteconfig operator, we will need to update the ClusterInstance template and upversion the IMS operator to support the new fields.
Given this, we could switch to rendering the ClusterInstance into the ClusterInstance struct type imported from the siteconfig package instead of using the unstructured type, which will simplify data manipulation. It's safe to directly manipulate with the ClusterInstance data, as the non-empty parameters have been verified in the ClusterInstance template and validated with dry-run previously.
When we need to update the ClusterInstance template to support new fields, the imported siteconfig package should be upversioned as well.
=> CNF-14301: Change the rendered ClusterInstance's type to siteconfig.ClusterInstance

bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/rbac/role.yaml, internal/controllers/orano2ims_controller.go
This adds a clusterrole to the Resource Server so that it has permission to access data via the ACM search-api.
=> MGMT-18924: Add RBAC role to Resource Server

internal/controllers/clusterrequest_controller.go, internal/controllers/clusterrequest_controller_test.go, internal/controllers/suite_test.go, internal/controllers/utils/utils_test.go
Currently, invalid configuration input causes resource preparation to fail, stopping the controller reconciliation. However, if Cluster deployment resources (NodePool, ClusterInstance, or Policies) have already been created and are in progress, subsequent invalid configuration changes should not prevent the controller from continuing to track the current Cluster deployment status.
This update ensures that the controller checks the Cluster deploy and config status when an input issue occurs during resource preparation before stopping reconciliation.
Unittests are added for ClusterRequest controller reconciliation to verify desired conditions.
=> CNF-14537: Ensure Cluster deploy and config status check on input issues during resource preparation

bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/samples/v1alpha1_clustertemplate.yaml, internal/controllers/clusterrequest_controller_test.go, internal/controllers/clustertemplate_controller.go, internal/controllers/utils/utils_test.go, internal/files/controllers/clusterinstance-template.yaml
bmcAddress, bmcCredentialsName, bootMACAddress, and nodeNetwork.interfaces[*].macAddress are meant to come from the NodePool (hardware) and should not be exposed in the ClusterRequest when hw plugin is fully utilized.
Placeholders for these fields have been added to pass the ClusterInstance dry-run validation since they are required fields. These placeholders will be replaced with data retrieved from NodePool later on.
Before hw plugin is fully utilized, these fields can still be provided through the ClusterRequest.
Remove the creation of ClusterInstance template configmap since the configmap is useless.
=> Add placeholders for values that come from NodePool

config/manager/kustomization.yaml, config/manager/manager.yaml, internal/cmd/operator/start_controller_manager.go, internal/controllers/utils/utils.go
This allows the --image parameter to default to whatever image reference has been specified in the IMAGE environment variable.  This is to facilitate the midstream build overlay which will set the image to be used to the official image reference.
=> CNF-13594: Use IMAGE env variable as default image

internal/controllers/clusterrequest_controller.go, internal/controllers/utils/utils.go, internal/controllers/utils/utils_test.go
In normal cases, ClusterInstance input data from the ClusterRequest overrides the defaults from the configmap. However, for the fields extraLabels and extraAnnotations, the default values from the configmap should take precedence if the same labels/annotations exist in both. The extraLabels provided in the default configmap are specific to the templated policies. They shouldn’t be overridden by ClusterRequest.
Add a function to handle these special overrides. If extraLabels or extraAnnotations are present in both the ClusterRequest and the configmap, the values from ClusterRequest will be overriden with the defaults.
The utility merge function is invoked after to perform the normal merging behavior, where ClusterRequest overrides defaults if both exist.
=> CNF-14376: Handle special overrides for extraLabels and extraAnnotations

api/v1alpha1/clusterrequest_types.go, bundle/manifests/o2ims.oran.openshift.io_clusterrequests.yaml, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/crd/bases/o2ims.oran.openshift.io_clusterrequests.yaml, config/manifests/bases/oran-o2ims.clusterserviceversion.yaml, config/samples/v1alpha1_clusterrequest.yaml, config/samples/v1alpha1_clustertemplate.yaml, internal/controllers/clusterrequest_controller.go, internal/controllers/clusterrequest_controller_test.go
- Replace clusterTemplateRef with two new fields - templateName and templateVersion, which represent the referenced ClusterTemplate.
- The name of ClusterTemplate should be formatted as <templateName.templateVersion>
=> CNF-14658: Replace clusterTemplateRef field with templateName and templateVersion

config/samples/testing/client-service-account-rbac.yaml
Missing permission to contact the  /o2ims-infrastructureInventory/v1 API.
=> Requires permission to contact the /o2ims-infrastructureInventory/v1

Makefile
Updated Makefile to add kubectl target dependencies for all targets using KUBECTL
=> NO-ISSUE: Fix Makefile targets using KUBECTL

internal/controllers/inventory_controller.go
The fact that we were using a "patch" operation on services is leading to some errors in the reconcile loop.  The "patch" should be reserved to use cases where we read an object from the system, make some changes to our local copy, and then want to "patch" it using the API to only send those fields that have changed.  What we were doing was creating a brand new object and attempting to "patch" that against what the running system already had which lead to trying to delete several runtime only attributes which I believe is what was leading to the errors.
=> Change operation type to update for services

internal/controllers/utils/constants.go, internal/controllers/utils/utils.go, internal/controllers/utils/utils_test.go
For the fields (bmcAddress, bmcCredentialsName, bootMACAddress, and nodeNetwork.interfaces[*].macAddress) that come from NodePool, we should just ignore changes to those fields.
=> CNF-13703: Ignore ClusterInstance immutable fields for vars from NodePool

hack/update_deps.sh
The api/hardwaremanagement folder is exported as a submodule for use by the oran-hwmgr-plugin, with its own go.mod and go.sum files. Should anything be changed in the submodule that impacts imports, it is important that the go.mod and go.sum are updated. By extending the hack/update_deps.sh to include a `go mod tidy` in the subfolder, we ensure that any missing changes are caught by the `ci-job` test to prevent issues.
=> NO-ISSUE: Update hack/update_deps.sh to handle exported API submodule

Dockerfile.tools
Due to the way CI is setup, the Dockerfile.tools file must be updated with new packages installed before those packages can be used in CI. ie. if adding tools to ci-job test that require additional packages, the Dockerfile.tools update must be merged first.
=> NO-ISSUE: Install additional packages in base image for CI

Makefile
If the kubectl target was previously executed (e.g., through make undeploy or make deploy) and the symbolic link $(LOCALBIN)/kubectl exists, subsequent make commands would fail at chmod u+w $(LOCALBIN) due to the inability to change permissions on the symbolic link. Removing the unnecessary -R option from chmod resolves this issue by avoiding recursive permission changes on symbolic links within $(LOCALBIN).
=> Remove unnecessary -R option for chmod command

Makefile
Addresses an issue created by reusing the docker-push target incorrectly which lead to the controller image being pushed rather than the bundle image.
=> Fix bundle-push target

Makefile, api/hardwaremanagement/v1alpha1/node.go, api/hardwaremanagement/v1alpha1/node_pools.go, api/provisioning/v1alpha1/clustertemplate_types.go, api/provisioning/v1alpha1/provisioningrequest_types.go, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/manifests/bases/oran-o2ims.clusterserviceversion.yaml, config/samples/kustomization.yaml, config/samples/v1alpha1_clustertemplate.yaml, config/samples/v1alpha1_inventory.yaml, config/samples/v1alpha1_node.yaml, config/samples/v1alpha1_nodepool.yaml, config/samples/v1alpha1_provisioningrequest.yaml, vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/node.go, vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/node_pools.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/clustertemplate_types.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_types.go
This update adds sample CRs for Node and NodePool, and adds status fields to other sample CRs that were missing it.
In addition, API markers have been added to spec and status fields where they were previously missing, to address scorecard warnings and suggestions.
=> NO-ISSUE: Add missing sample CRs, address scorecard suggestions

Dockerfile, Makefile, README.md, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/debug/disable-health-probes.yaml, config/debug/disable-leader-election.yaml, config/debug/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml
This adds the changes required so that a developer can build an image capable of using the DLV debugger to debug any of the deployed servers or controller.
Some functionality needed to be disabled in order to make suspending the program being debugged possible (i.e., health checks,
leader election, etc).  This is only true if DEBUG=yes when the build command is executed.
=> Proposal: Add DLV debugging capabilities

api/hardwaremanagement/v1alpha1/node.go, api/hardwaremanagement/v1alpha1/node_pools.go, api/provisioning/v1alpha1/clustertemplate_types.go, api/provisioning/v1alpha1/provisioningrequest_types.go, bundle/manifests/o2ims-hardwaremanagement.oran.openshift.io_nodepools.yaml, bundle/manifests/o2ims-hardwaremanagement.oran.openshift.io_nodes.yaml, bundle/manifests/o2ims.provisioning.oran.org_clustertemplates.yaml, bundle/manifests/o2ims.provisioning.oran.org_provisioningrequests.yaml, config/crd/bases/o2ims-hardwaremanagement.oran.openshift.io_nodepools.yaml, config/crd/bases/o2ims-hardwaremanagement.oran.openshift.io_nodes.yaml, config/crd/bases/o2ims.provisioning.oran.org_clustertemplates.yaml, config/crd/bases/o2ims.provisioning.oran.org_provisioningrequests.yaml, vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/node.go, vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/node_pools.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/clustertemplate_types.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_types.go
Description:
- add `oranct`, `oranpr`, `onrannode` and `orannp` as shortnames
- add printcolumns for all CRs to show their age and main conditions
Examples:
```
$  oc get oranct -A
NAMESPACE                 NAME                   AGE     STATE       DETAILS
clustertemplate-a-v4-16   clustertemplate-a.v1   4d21h   Completed   The cluster template validation succeeded
clustertemplate-a-v4-16   clustertemplate-a.v2   4d21h   Completed   The cluster template validation succeeded
$  oc get oranpr
NAME      AGE     HW PROVISIONING   INSTALLATION   CONFIGURATION
cnfdg11   2m10s   Completed         InProgress     ClusterNotReady
$  oc get orannode -A
NAMESPACE                NAME      AGE    STATE
oran-hwmgr-plugin-test   cnfdg11   2m8s   Completed
$  oc get orannp -A
NAMESPACE …
```
=> NO-ISSUE: Add shortnames for ORAN CRs

internal/cmd/server/start_resource_server.go, internal/graphql/graphql.go, internal/graphql/graphql_test.go, internal/openapi/spec.yaml, internal/service/alarm_handler_test.go, internal/service/alarm_mapper.go, internal/service/resource_fetcher.go, internal/service/resource_handler.go, internal/service/resource_handler_test.go, internal/service/resource_pool_fetcher.go, internal/service/resource_pool_handler_test.go, internal/service/resource_type_handler.go, internal/service/resource_type_handler_test.go
The returned fields for some API endpoints are returning incorrect field names based on the specification (O-RAN 2IMS INTERFACE v6 spec). See for instance tables:
- Table 2.1.1.1.3-1: Attributes of the ResourceType
- Table 2.1.1.1.4-1: Attributes of the ResourcePool
- Table 2.1.1.1.5-1: Attributes of the Resource
This fix modifies the returned value and replaces:
- resourceTypeID by resourcetTypeId
- globalLocationID by globalLocationId
- resourcePoolID by resourcePoolId
With these changes, some faulty [O2IMS Compliance Test](https://github.com/o-ran-sc/it-test/tree/master/test_scripts/O2IMS_Compliance_Test) pass. 
PD. For testing you can use my ORAN-O2IMS operator image, which already contains the fix at quay.io/alosadag/oran-o2ims:v4.16.1
=> Aligns with the expected returned field names specified in the specification

docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v1.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v2.yaml, internal/controllers/provisioningrequest_controller.go, internal/controllers/provisioningrequest_controller_test.go, internal/controllers/utils/hardware_utils.go, internal/controllers/utils/types.go, internal/controllers/utils/utils.go
This update adds a label for each interface specified in the default cluster instance ConfigMap. The label is used to match the corresponding interface label returned by the hardware manager. Upon finding a match, the returned MAC address is assigned to the respective interface in the rendered cluster instance.
Additionally, this update moves hardware provisioning-specific utility functions to a separate file for improved organization and clarity.
=> Add Interface Label to clusterinstance-defaults

internal/service/resource_type_handler.go
According to the O2ims Interface Specification document we are missing the field "description" as an attribute of the resourceType. See Table 2.1.1.1.3-1: Attributes of the ResourceType in the O-RAN WG6 O2IMS INTERFACE document.
I just added the description field returning an empty value in order to pass the conformance tests.
=> Missing required field "description" in resourceType attribute

docs/samples/git-setup/policytemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-pg-v4-Y-Z-v1.yaml, docs/samples/git-setup/policytemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-pg-v4-Y-Z-v2.yaml, internal/controllers/utils/conditions.go
A few updates:
- Add du validator policy in the PGs and set `evaluationInterval` to `never` for compliant so that the policy is not re-evaluated after it becomes compliant (to match with the legacy ZTP). We will also try out the configuration policy event-driven feature [ACM-11666](https://issues.redhat.com/browse/ACM-11666) introduced in ACM 2.12 for all policies.
- Remove `consolidateManifests: false` since all manifests added in a single policy have no dependencies and should be able to apply in parallel.
- Treat Cluster installation as completed when ClusterInstance status condition reason has `staleCondition`. As described in the comment, that is due to issue [ACM-13064](https://issues.redhat.com/browse/ACM-13064). In this case, the cluster is actually installed successfully and …
=> NO-ISSUE: Add validator du policy in the PG examples

internal/controllers/provisioningrequest_clusterconfig_test.go, internal/controllers/provisioningrequest_controller.go, internal/controllers/provisioningrequest_setup.go, internal/controllers/utils/utils.go
Description:
- Handle ClusterTemplate Create, Update and Delete events in the provisioningrequest controller.
- Trigger provisioningrequest reconciliation if such events come from a ClusterTemplate used by a ProvisioningRequest.
- For ClusterTemplate Create events, only process them further if the ClusterTemplate status has been filled in. If the status is empty it will not impact the ProvisioningRequest since we need a validated ClusterTemplate.
- Switch to using `handler.EnqueueRequestsFromMapFunc` for watching ClusterInstances, ClusterTemplates, Policies, NodePools, ManagedClusters.
- Watch ManagedClusters only if there's a change in their availability.
- Unrelated changes: remove some logs from the  `doesK8SResourceExist` and `CreateK8sCR` functions.
=> CNF-15056: Improve watches in the PR controller

internal/controllers/provisioningrequest_clusterconfig.go, internal/controllers/provisioningrequest_clusterconfig_test.go, internal/controllers/provisioningrequest_controller.go, internal/controllers/suite_test.go
Do not periodically requeue if there are NonCompliant policies in enforce, but we have reached Timeout.
If the policies become Compliant in the meantime, IMS will get triggered and it will reconcile.
=> NO-ISSUE: Do not reconcile on config timeout

bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/rbac/role.yaml, internal/controllers/inventory_controller.go
This adds resources to the RBAC role to allow servers to query managed data from the search api; otherwise, the servers can only query data that was collected on the hub and not any of the data collected on the managed clusters.
=> CNF-15167: Fix RBAC role for searching managed data

docs/cluster-provisioning.md, docs/samples/git-setup/clustertemplates/hardwaretemplates/sno-ran-du/placeholder-du-template-configmap-v1.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v1.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v2.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v3.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v4.yaml, internal/controllers/clustertemplate_controller.go, internal/controllers/clustertemplate_controller_test.go, internal/controllers/provisioningrequest_clusterconfig_test.go, internal/controllers/provisioningrequest_controller_test.go, internal/controllers/provisioningrequest_validation.go, internal/controllers/utils/constants.go
- Rename the timeout config key for cluster install from `clusterProvisioningTimeout` to `clusterInstallationTimeout` to avoid confusion (since cluster provisioning refers to the process from hw provisioning to cluster configuration).
- Add a brief description for timeout.
=> No-ISSUE: cluster install timeout rename and doc updates for timeout

internal/controllers/clustertemplate_controller.go, internal/controllers/provisioningrequest_clusterconfig_test.go, internal/controllers/provisioningrequest_clusterinstall.go, internal/controllers/provisioningrequest_clusterinstall_test.go, internal/controllers/provisioningrequest_controller.go, internal/controllers/provisioningrequest_controller_test.go, internal/controllers/provisioningrequest_hwprovision_test.go, internal/controllers/provisioningrequest_resourcecreation.go, internal/controllers/provisioningrequest_resourcecreation_test.go, internal/controllers/provisioningrequest_setup.go
Switch to use ownerReference to simplify the resources cleanup and watchers:
- Set the ProvisioningRequest as the owner for its created resources that haven't been set yet
- Remove finalizers
- Remove watch mappers for NodePool and ClusterInstance
=> CNF-15060: Switch to use ownerReference for ProvisioningRequest created CRs

docs/cluster-provisioning.md, internal/controllers/provisioningrequest_controller_test.go, internal/controllers/utils/conditions.go
Update the message for fulfilled state to be more generic that fits all scenarios.
=> NO-ISSUE: Update message for fulfilled state to be more generic

bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/samples/v1alpha1_clustertemplate.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v1.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v2.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v3.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v4.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-v4-Y-Z-1.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-v4-Y-Z-2.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-v4-Y-Z-3.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-v4-Y-Z-4.yaml, internal/controllers/provisioningrequest_clusterconfig_test.go, internal/controllers/provisioningrequest_clusterinstall_test.go, internal/controllers/provisioningrequest_controller.go, internal/controllers/provisioningrequest_controller_test.go, internal/controllers/provisioningrequest_hwprovision.go, internal/controllers/provisioningrequest_resourcecreation.go, internal/controllers/utils/provision.go
With this commit, HW manager plugin([loopback adaptor](https://github.com/openshift-kni/oran-hwmgr-plugin/blob/main/adaptors/loopback/README.md)) is required for cluster provisioning.
Updates included:
- Remove the checks for `hwgmr` ns that could bypass the HW manager plugin
- Remove the workaround code for `hwgmr` ns creation originally for unittest(ns is now created within unittests)
- Remove the workaround code for BMC secret creation
- ClusterInstance Schema updates in the ClusterTemplate samples:
- Remove `BMC` related parameters, `bootMacAddress` and the entire `nodeNetwork.interfaces` (name should be added in the default ClusterInstance configmap)
- Remove `rootDeviceHints` from schema, adding it to the default ClusterInstance configmap
- Fix an issue with updating the overall …
=> CNF-13704: fully utilize HW manager plugin for cluster provision

internal/service/resource_handler.go
As detailed in **Table 2.1.1.1.5-1: Attributes of the Resource** from the O-RAN WG6 O2IMS Interface the Attribute elements is mandatory and it was missing in the returning information.
Notice that the description of this field says that the resource might be composed of smaller resources or other resource instances. Also, the conformance tests are expecting an array. Therefore I created an empty array of strings to include the elements attribute and pass the tests. Let me know if there is a way to include an array of type Resources instead (I did not find the proper way) if it makes sense.
cc/ @alegacy
=> Adds missing "elements" array to the attributes of a Resource

docs/cluster-provisioning.md, internal/controllers/clustertemplate_controller.go, internal/controllers/clustertemplate_controller_test.go, internal/controllers/provisioningrequest_controller_test.go, internal/controllers/provisioningrequest_hwprovision.go, internal/controllers/utils/conditions.go, internal/controllers/utils/hardware_utils.go, internal/controllers/utils/provision.go
This update introduces the HardwareNodeConfigApplied status in the Provisioning Request to signify that essential hardware node attributes—such as BMC details, interface MAC addresses, and the boot MAC address—have been successfully applied to the Cluster Instance. A failure status may be triggered if incorrect interface labels are provided or if a mismatched boot interface label is specified that conflicts with the defined hardware profile. This status serves as an indication for users to verify and adjust their configuration if necessary.
Additionally, this update includes a validation check for missing or empty interface labels within the cluster instance default map, ensuring accurate configuration and alignment with hardware requirements.
=> Add HardwareNodeConfigApplied status to Provisioning Request

go.mod, internal/controllers/provisioningrequest_clusterinstall.go, internal/controllers/provisioningrequest_controller_test.go, internal/controllers/provisioningrequest_upgrade.go, internal/controllers/suite_test.go, internal/controllers/utils/constants.go
For upgrade process AgentClusterInstall should be added to
ClusterInstance's suppressedManifests in order to prevent updates to it.
This commit fixes suppressedManifests getting removed on subsequent
reconciles after adding on the first reconcile.
=> Fix suppressedManifests getting removed

api/provisioning/v1alpha1/provisioningrequest_types.go, bundle/manifests/o2ims.provisioning.oran.org_provisioningrequests.yaml, config/crd/bases/o2ims.provisioning.oran.org_provisioningrequests.yaml, docs/cluster-provisioning.md, internal/controllers/provisioningrequest_clusterconfig_test.go, internal/controllers/provisioningrequest_controller.go, internal/controllers/provisioningrequest_controller_test.go, internal/controllers/provisioningrequest_setup.go, internal/controllers/utils/conditions.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_types.go
Updates included:
- Add new provisioningState `deleting`, set when ProvisioningRequest is marked for deletion.
- Add the finializer back to handle dependents deletion, ensuring dependents are removed before removing finalizer from ProvisioningRequest to complete the deletion.
- Watch for deletion of cluster namespace so reconcilation can be triggered when ns is deleted.
=> CNF-15491: Handle ProvisioningRequest deletion

internal/service/alarm_definition_handler.go, internal/service/alarm_definition_handler_test.go
These fields are missing as part of the AlarmDefinition table (Table 3.2.6.2.9‑1 Definition of type AlarmDefinition) in the O-RAN WG6 O2-IMS INTERFACE document. They're mandatory fields that needs to be sent back to pass the conformance tests.
cc/ @pixelsoccupied @alegacy
=> Adds missing mandatory AlarmDefinition attributes

bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/manager/manager.yaml, internal/cmd/operator/start_controller_manager.go, internal/controllers/utils/constants.go, internal/controllers/utils/utils.go
Rather than get the namespace from the service account static files we are able to get it from an environment variable.  This benefits being able to run the controller from the command line for testing purposes.
=> MGMT-18997: Use downward API to acquire namespace

internal/controllers/utils/utils.go, internal/controllers/utils/utils_test.go
This changes how we acquire the default domain so that we look at the ingress controller's Status field rather than its Spec field since in some cases it may not be explicitly set in the Spec which causes it to go get it from another source.  Ultimately, we do not care where it gets it from so we look at its final decision which is stored in the Status field.
=> MGMT-18997: Get default domain from status rather than spec

api/hardwaremanagement/v1alpha1/node_pools.go, api/hardwaremanagement/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/o2ims-hardwaremanagement.oran.openshift.io_nodepools.yaml, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/crd/bases/o2ims-hardwaremanagement.oran.openshift.io_nodepools.yaml, config/manifests/bases/oran-o2ims.clusterserviceversion.yaml, config/samples/v1alpha1_nodepool.yaml, internal/controllers/provisioningrequest_hwprovision.go, internal/controllers/utils/hardware_utils.go, vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/node_pools.go, vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/zz_generated.deepcopy.go
This update removes node pool status updates from the Cloud Manager to maintain a clear separation of responsibilities: the Cloud Manager exclusively updates spec fields, while the hwMgr plugin is responsible for status fields.
The hwMgr plugin uses the ObservedGeneration status field to detect changes in the node pool spec and adjust its operations accordingly, without needing to modify spec fields. This design strengthens single-responsibility principles, reducing potential update conflicts.
=> Remove NodePool Status Updates from Cloud Manager

api/provisioning/v1alpha1/clustertemplate_types.go, bundle/manifests/o2ims.provisioning.oran.org_clustertemplates.yaml, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/crd/bases/o2ims.provisioning.oran.org_clustertemplates.yaml, config/samples/v1alpha1_provisioningrequest.yaml, docs/cluster-provisioning.md, docs/samples/git-setup/clustertemplates/version_4.Y.Z/kustomization.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-v4-Y-Z-1-no-hwtemplate.yaml, internal/controllers/clustertemplate_controller.go, internal/controllers/provisioningrequest_clusterconfig_test.go, internal/controllers/provisioningrequest_clusterinstall_test.go, internal/controllers/provisioningrequest_controller.go, internal/controllers/provisioningrequest_resourcecreation.go, internal/controllers/provisioningrequest_resourcecreation_test.go, internal/controllers/provisioningrequest_validation.go, internal/controllers/provisioningrequest_validation_test.go, internal/controllers/utils/provision_test.go, internal/files/controllers/clusterinstance-template.yaml, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/clustertemplate_types.go
In the case where hwTemplate is not provided, hw provisioning is skipped and only cluster installation and configuration will be performed.  The hardware-related parameters (such as bmcAddress, bmcCreds - username and password are all base64-encoded strings, bootMacAddress, nodeNetwork macAddress) should instead be passed in the ProvisioningRequest. The ClusterTemplate schema should include these parameters, allowing them to be specified in the ProvisioningRequest.
Updates:
- change `templates.hwTemplate` to be optional
- skip hw provisioning when hwTemplate is not provided
- create BMC secret when hwTemplate is not provided
- add example ClusterTemplate without hwTemplate
Todo:
Consider validating the schema to ensure that the hardware-related parameters are present and marked as …
=> CNF-15608: Support cluster provisioning without hwTemplate

internal/service/alarms/cmd/root.go
Originally it was incorrectly initializing the logger for all CLI commands (root/sub)...as init func is called regardless of which  cmd is executed. `PersistentPreRun` should be used instead so that alarms logging is initialized as long as alarm's sub commands are called (serve or migrate) 
/cc @alegacy
=> fix incorrect init of logger for alarms server

internal/controllers/clustertemplate_controller.go, internal/controllers/clustertemplate_controller_test.go, internal/controllers/provisioningrequest_resourcecreation.go, internal/controllers/provisioningrequest_resourcecreation_test.go
Description:
- check that spec.policyTemplateParameters in a ClusterTemplate has only properties of type string. This ensures that the PGs will decide the final type by using toInt/toLiteral.
- ClusterTemplate validation errors appear in the status:
```console
$  oc get oranct -A
NAMESPACE            NAME                   AGE     STATE       DETAILS
sno-ran-du-v4-17-3   sno-ran-du.v4-17-3-1   2m48s   Failed      Error validating the policyTemplateParameters schema: expected type string for the sriov-network-vlan-1 property
```
=> CNF-15631: policyTemplateParameters in a CT has only string type properties

internal/controllers/provisioningrequest_clusterconfig.go, internal/controllers/provisioningrequest_clusterconfig_test.go, internal/controllers/provisioningrequest_controller_test.go, internal/controllers/provisioningrequest_setup.go, internal/controllers/utils/provision.go
The controller should only handle/consider the child policies whose parent policies are from the `ztp-<clustertemplate-ns> `namespace. Other bound policies should neither trigger the reconcilation nor be considered in the policy configuration process.
=> CNF-15660: Filter out policies outside the ztp-<clustertemplate-ns> namespace

internal/service/postgres/k8s/base/deployment.yaml
Last few weeks there was a bug in OCP that allowed for downloading rhel/pg-16 without any additional creds/accepting terms. This has been fixed...and now we cant download the image without additional steps. 
update to use registry.redhat.io instead
/cc @browsell 
/cc @alegacy 
/cc @mlguerrero12
=> fix: update pg image to use registry.redhat.io instead

README.md
This PR updates documentation:
- It divides the README into two main blocks: deployment via operator in OpenShift and local deployment (testing)
- Deployment of the IMS operator on top of OpenShift
- Configuration of the different microservices of the IMS operator using the ORANO2MS CR. There was no example of that CR in the repo.
- Currently only metadata, deployment manager and resource server. The rest could be added once they are validated in the operator deployment.
- An index is added to ease navigation through the information
Let me know your thoughts.
=> [doc] Adds operator deployment steps in OpenShift

Makefile, internal/service/alarms/internal/alarms_server.go, internal/service/alarms/internal/alertmanager/alertmanager.go, internal/service/alarms/internal/alertmanager/alertmanager.yaml, internal/service/alarms/internal/alertmanager/alertmanager_test.go, internal/service/alarms/internal/alertmanager/suite_test.go, internal/service/alarms/k8s/README.md, internal/service/alarms/k8s/base/endpoints.yaml, internal/service/alarms/k8s/base/kustomization.yaml, internal/service/alarms/k8s/base/service.yaml, internal/service/alarms/serve.go
Add a webhook receiver to AlertManager configuration so that alarm server is notified to the internal endpoint.
=> CNF-14862: Configure AlertManager to send alerts

internal/controllers/provisioningrequest_clusterconfig.go, internal/controllers/provisioningrequest_clusterconfig_test.go
For the ORAN use case, inform policies should only be used to validate cluster configurations. When all enforce and inform policies are compliant, the cluster configuration is considered complete, and provisioning can be fulfilled. Updated logic now includes inform policies in the configuration timeout calculation.
=> CNF-15661: Include inform policies in configuration timeout calculation

internal/controllers/inventory_controller.go, internal/controllers/utils/constants.go, internal/controllers/utils/utils.go, internal/service/common/db/migration.go
This commit adds the init container for the resource server.  The container runs prior to starting the resource server container so that its database schema is created and migrated up to the latest schema version.  The init container is run any time the resource server pod is recreated, and if there is a transient failure in the init due to a race condition in bringing up the database server it is automatically retried until it succeeds.
=> CNF-14144: Add migration init container for resource server

api/inventory/v1alpha1/inventory_types.go, bundle/manifests/o2ims.oran.openshift.io_inventories.yaml, config/crd/bases/o2ims.oran.openshift.io_inventories.yaml, internal/controllers/inventory_controller.go, internal/controllers/inventory_controller_test.go, internal/controllers/utils/constants.go, internal/controllers/utils/utils.go, internal/controllers/utils/utils_test.go, vendor/github.com/openshift-kni/oran-o2ims/api/inventory/v1alpha1/inventory_types.go
Rather than hardcode the name and namespace of the search-api service
this commit searches for it using its well-known search labels.  As is
currently the case, if a user provides an override on the Inventory CR
then we use that rather than searching for it.
=> Lookup search api URL dynamically

internal/service/alarms/internal/alarms_server.go
The panic is not handled properly which leads to 502 response from the proxy which is misleading.
=> Remove panic from unimplemented API calls

internal/controllers/inventory_controller.go
To better support development use cases where we want to always pull development images, but then also only pull production images once we can leverage the behaviour described at this location [1]
[1] https://spacelift.io/blog/kubernetes-imagepullpolicy#image-pull-policy
=> Unset pull policy to enable always pulling latest

bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/manager/manager.yaml, internal/controllers/utils/constants.go
This updates the name of the postgres image to have the RELATED_IMAGE_ prefix required by the midstream process.
=> Align postgres image var name with midstream process

Makefile
Update markdownlint image build command to make it work for both docker and podman.
=> NO-ISSUE: Quick fix for markdownlint image build with docker CLI

docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-v4-Y-Z-1-no-hwtemplate.yaml, internal/controllers/clustertemplate_controller.go, internal/controllers/clustertemplate_controller_test.go, internal/controllers/utils/provision.go
This update ensures that the schema contains required properties such as BMC details, bootMacAddress, interfaces, and other necessary fields for provisioningRequest to provide when hwtemplate is not specified.
=> CNF-15906: Add validation for clusterInstanceParams schema without hwtemplate

internal/service/alarms/internal/db/migrations/000001_create_alarm_dictionary_table.up.sql, internal/service/alarms/internal/db/migrations/000002_create_alarm_definition_table.up.sql, internal/service/alarms/internal/db/models/alarm_definition.go, internal/service/alarms/internal/db/models/alarm_dictionary.go, internal/service/alarms/internal/db/models/alarm_event_record.go, internal/service/alarms/internal/db/repo/alarms_repository.go, internal/service/alarms/internal/dictionary/dictionary.go, internal/service/alarms/serve.go, internal/service/common/db/models.go, internal/service/common/utils/repository.go, internal/service/common/utils/utils_test.go, internal/service/resources/db/models/deployment_manager.go, internal/service/resources/db/models/resource.go, internal/service/resources/db/models/resource_pool.go, internal/service/resources/db/models/resource_type.go, internal/service/resources/db/models/subscription.go, internal/service/resources/db/repo/repository.go
It deletes alarm dictionaries that do not have a
corresponding resource type object and for the ones that do, inserts or updates the collected rules
=> CNF-15659: Sync Alarm dictionaries in DB

internal/service/alarms/internal/db/migrations/000001_create_alarm_dictionary_table.up.sql, internal/service/alarms/internal/db/migrations/000002_create_alarm_definition_table.up.sql, internal/service/alarms/internal/db/migrations/000003_create_alarm_event_record_table.up.sql, internal/service/alarms/internal/db/migrations/000005_create_alarm_subscription_info_table.up.sql
CREATE TRIGGER fails if the trigger already exists
=> Add REPLACE to trigger creation during alarm DB up migration

config/testing/client-service-account-rbac.yaml
Fixes the test client service account RBAC to be able to access the alarm and subscription endpoints.
=> CNF-15570: Fix test client RBAC

hack/golangci-lint.sh, internal/controllers/clustertemplate_controller.go, internal/controllers/provisioningrequest_clusterinstall.go, internal/controllers/provisioningrequest_controller.go, internal/controllers/provisioningrequest_validation.go, internal/controllers/utils/hardware_utils.go, internal/jq/query.go, internal/service/subscription_handler.go
This update upgrades golangci-lint to 1.62.2 and resolves the linting errors.
=> upgrade golangci-lint to 1.62.2

internal/controllers/clustertemplate_controller_test.go, internal/controllers/utils/provision.go
Fix the indention of ClusterInstanceParameter schema for schema validation in the no hwtemplate case.
=> CNF-15906: Fix the indention of clusterInstanceParameters schema

internal/service/alarms/internal/alarms_server.go, internal/service/alarms/internal/db/migrations/000005_create_alarm_subscription_info_table.up.sql, internal/service/resources/api/server.go, internal/service/resources/db/migrations/000001_baseline.up.sql
The conformance tests expect a 400 status code if a duplicate subscription is requested.  A 409 status code is a more common choice for this type of error condition but since the tests look for a 400 we are sort of bound by that.
=> CNF-15570: Add unique constraint to subscriptions

.github/dependabot.yml
The major/minor updates for k8s.io repos require go 1.23. This update adds an ignore for such updates for dependabot, which can be removed when the plugin is updated to 1.23 as well
=> NO-ISSUE: Configure dependabot to ignore k8s.io major/minor updates for now

internal/service/common/notifier/event.go, internal/service/common/notifier/notifier.go, internal/service/common/notifier/notifier_worker.go, internal/service/resources/api/server.go, internal/service/resources/collector/collector.go, internal/service/resources/collector/collector_acm.go, internal/service/resources/db/migrations/000001_baseline.up.sql, internal/service/resources/db/models/converters.go, internal/service/resources/db/models/data_change_event.go, internal/service/resources/db/models/subscription.go, internal/service/resources/db/repo/notifications.go, internal/service/resources/db/repo/repository.go, internal/service/resources/db/repo/subscriptions.go, internal/service/resources/serve.go, internal/service/resources/utils/constants.go
This adds support for sending notifications to a subscriber whenever a data change event occurs.  This applies to all the supported inventory object (i.e., resource types, resource pools, resources, and deployment managers).
If the subscriber is not reachable then a number of retries are attempted.  If at the end of the retries the subscriber is still not reachable then the event notification is retired and the notifier moves on to the next event in the list.  This behaviour should likely be changed so that if the subscriber is unreachable for a set period of time then the subscription should be put in an 'offline' state and should ignore new events for some period of time to avoid excess error
logs.   This is left for a future commit.
=> CNF-15570: Add notification support

internal/service/alarms/serve.go, internal/service/common/api/middleware.go, internal/service/resources/serve.go
The default 404 handler on the router generates a text response, but the ORAN spec requires a JSON response.  This adapts the output to be a JSON response with the appropriate content type header.
=> CNF-15570: Set default 404 handler

config/testing/client-service-account-rbac.yaml
This adjusts the test client RBAC rules so additional operations are supported by the test client.  These are necessary to pass the conformance tests.
=> CNF-15570: Set RBAC rules for test client

internal/service/alarms/serve.go, internal/service/common/api/filtering.go, internal/service/resources/serve.go
This ports the existing include/exclude field filter as well as the record filter from the existing API implementation to the new API implementation for both the alarm and resource servers.  See the common openapi.yaml file for more information on the functioning of the query parameters for 'fields', 'exclude_fields', and 'filter' parameters.
The 'filter' functionality should eventually be integrated directly into the database queries to limit the number of results directly at the source rather than post-processing the result which is far more expensive. The current approach is a temporary solution to achieve parity with the existing API implementation with the least amount of cost.
=> CNF-15750: Add field and record filtering to new API servers

internal/controllers/utils/constants.go, internal/service/cluster/collector/collector_k8s.go
This adds some extensions to the NodeClusterType to better identify what type of NodeCluster the NodeClusterType represents.  These fields will be consumed by the alarm server to define the alarm dictionary for each NodeClusterType.
=> CNF-16217: Add extensions to NodeClusterType

config/testing/client-service-account-rbac.yaml, internal/service/alarms/api/generated/alarms.generated.go, internal/service/alarms/api/openapi.yaml, internal/service/alarms/internal/alarms_server.go, internal/service/alarms/internal/db/migrations/000006_create_alarm_service_configuration_table.down.sql, internal/service/alarms/internal/db/migrations/000006_create_alarm_service_configuration_table.up.sql, internal/service/alarms/internal/db/models/alarm_service_configuration.go, internal/service/alarms/internal/db/models/converters.go, internal/service/alarms/internal/db/repo/alarms_repository.go, internal/service/alarms/serve.go
This implements the alarm service configuration endpoints. The specification defines GET, PUT (only update, not create) and PATCH operations. Therefore, we create a default service configuration at startup. The spec also mentions that the retention period has a minimum value which is not explicitly defined. We assume 10 and 1 as default and minimum retention periods respectively. The values represent days.
=> CNF-16177: Implement Alarm Service Configuration endpoints

Makefile
Needed to force `linux/amd64` as my local platform is arm64. This should help so we don't have specify it separately. 
/cc @donpenney
=> add a default build platform for regular build command

internal/service/alarms/api/server.go, internal/service/alarms/internal/db/migrations/000003_create_alarm_event_record_table.up.sql
This addresses the following:
- When alarm is cleared, the changed time is equal to the cleared time to properly show that the record was updated due to this and not give the impression that a subsequent change was made.
- When an acknowledged alarm is resolved, the change time is not updated.
- Handle alarm_change_time column only in the trigger. Remove setting this on the API.
- Have a consistent behavior. When an alarm is created, the changed time is equal to the raised time. When it is resolved, the change time is equal to the cleared time. When it is acknowledged, the change time is equal to the change time. Any other updates have CURRENT_TIMESTAMP set by the trigger
=> Handle alarm_change_time only on trigger for all operations

internal/service/artifacts/api/server.go, internal/service/artifacts/cmd/root.go, internal/service/artifacts/cmd/serve.go, internal/service/artifacts/serve.go, internal/service/common/clients/k8s/k8s.go, internal/service/resources/api/server.go, main.go
Description:
- Implement the artifacts server and the code for getting all the `ClusterTemplates` from a hub cluster
- The ClusterTemplates are converted to the `ManagedInfrastructureTemplate` format by following the rules:
```
clustertemplate.name                    -> managedInfrastructureTemplate.name
clustertemplate.version                 -> managedInfrastructureTemplate.version
clustertemplate.description             -> managedInfrastructureTemplate.description 
clustertemplate.templateParameterSchema	-> managedInfrastructureTemplate.parameterSchema
clustertemplate.templateId              -> managedInfrastructureTemplate.artifactResourceId
```
- For local runs (the only supported method so far):
```console
./bin/oran-o2ims artifacts-server serve
curl …
```
=> CNF-16193: Templates REST API internal server - GET ALL

bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/debug/disable-health-probes.yaml, config/debug/disable-leader-election.yaml, config/debug/manager_config_patch.yaml, config/default/kustomization.yaml, config/default/manager_webhook_patch.yaml, config/manager/manager.yaml
The introduction of the webhook validation affected the ability to build with DEBUG=yes so this commit re-arranges how the lists are defined and patched to work around the issue.
=> Fix kustomize layering for debug mode

internal/service/artifacts/api/server.go, internal/service/artifacts/serve.go
Description:
- Add a ResponseFilter to the artifacts server to enable filtering on GET requests.
- Map the managedInfrastructureTemplate Name to Cluster Template Spec.Name instead of Metadata.Name.
- Example curl:
```console
curl \
-X 'GET' \
'http://127.0.0.1:8000/o2ims-infrastructureArtifacts/v1/managedInfrastructureTemplates?filter=(eq,version,v4-17-3-1)%3b(eq,name,sno-ran-du)' \
-H 'accept: application/json' | jq
```
=> CNF-16194: Add filtering to the artifacts server

internal/service/cluster/api/server.go, internal/service/cluster/collector/collector.go, internal/service/cluster/collector/collector_k8s.go, internal/service/cluster/db/migrations/000001_baseline.up.sql, internal/service/cluster/db/models/cluster_resource.go, internal/service/cluster/db/models/converters.go, internal/service/cluster/db/repo/repository.go
This adds the ability to return the list of cluster resource id values as part of an API query for node cluster(s).  These values are not persisted to the database, but are queried on an as-needed basis in response to an API query.
=> CNF-16246: Add list of cluster resources to node cluster

internal/service/common/notifier/notifier.go, internal/service/common/notifier/notifier_worker.go
The design of the notifier and notifier worker interactions was flawed in that it allowed the possibility of a deadlock whenever both the worker's work channel and notifier's completion channel buffers were full.  The notifier cannot send new work to the worker, and the worker gets stuck waiting for the notifier to acknowledge receipt of the completion event.
This is being mitigated by having the notifier enqueue work onto the worker's work queue directly, and only signaling the work channel upon adding the first event onto the queue.  The worker will independently process the queue and report completion down to the notifier.  This should eliminate the possibility that the completion channel fills up and the worker blocking indefinitely.
=> Fix notifier deadlock on new events

internal/service/alarms/api/server.go, internal/service/cluster/api/server.go, internal/service/cluster/collector/collector.go, internal/service/common/notifier/notifier.go, internal/service/common/notifier/notifier_worker.go, internal/service/resources/api/server.go, internal/service/resources/collector/collector.go
The input channels to the notifier for subscription or notification events assume that the write to the channel will always succeed.  Since we used buffered channels, and we know that there are use cases where many events may be in-flight simultaneously, it is conceivable that the notifier back-pressures back to the source of the events.  If this happens, then the event source blocks until the channel becomes available to receive a new message.
If this condition is present while the process is shut down, then the source go routine will hang waiting to send to the channel(s).  By incorporating the channel write into a select that also considers the state of the context; then we are able to abort a blocked send if the source go routine is canceled.
=> Fix notifier related hangs on shutdown

internal/controllers/utils/utils.go
Fixes a panic due to a nil pointer deference when testing against an SMO without using a client TLS certificate for mTLS.
=> Fix panic when not using client TLS to SMO

api/provisioning/v1alpha1/conditions.go, api/provisioning/v1alpha1/provisioningrequest_validation.go, api/provisioning/v1alpha1/provisioningrequest_webhook.go, internal/controllers/clustertemplate_controller.go, internal/controllers/clustertemplate_controller_test.go, internal/controllers/provisioningrequest_clusterconfig.go, internal/controllers/provisioningrequest_clusterconfig_test.go, internal/controllers/provisioningrequest_clusterinstall.go, internal/controllers/provisioningrequest_clusterinstall_test.go, internal/controllers/provisioningrequest_controller.go, internal/controllers/provisioningrequest_controller_test.go, internal/controllers/provisioningrequest_hwprovision.go, internal/controllers/provisioningrequest_hwprovision_test.go, internal/controllers/provisioningrequest_upgrade.go, internal/controllers/utils/conditions.go, internal/controllers/utils/hardware_utils.go, internal/controllers/utils/provision_test.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/conditions.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_validation.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_webhook.go
Move the ClusterTemplate and ProvisioningRequest condition types and reasons to the provisioning API package, so they can be used by both webhook and controller, potentially, referenced by external component if needed.
=> CNF-16211: Expose the CT and PR conditions in the provisioning API package

internal/service/artifacts/api/generated/artifacts.generated.go, internal/service/artifacts/api/openapi.yaml, internal/service/artifacts/api/server.go
Description:
- add support for getting the API version and minor versions
```console
$ curl -kq https://o2ims.apps.$MY_CLUSTER/o2ims-infrastructureArtifacts/api_versions -H "Authorization: Bearer ${MY_TOKEN}"  | jq
{
"apiVersions": [
{
"version": "1.0.0"
}
],
"uriPrefix": "/o2ims-infrastructureArtifacts/v1"
}
$ curl -kq https://o2ims.apps.$MY_CLUSTER/o2ims-infrastructureArtifacts/v1/api_versions -H "Authorization: Bearer ${MY_TOKEN}"  | jq
{
"apiVersions": [
{
"version": "1.0.0"
}
],
"uriPrefix": "/o2ims-infrastructureArtifacts/v1"
}
```
- add support for getting one `ManagedInfrastructureTemplate` by specifying the `ManagedInfrastructureTemplateId` in the request. `ManagedInfrastructureTemplateId` is currently compared to `<clusterTemplateName>.<clusterTemplateVersion>` (equal to …
=> CNF-16400: CNF-16401: Artifacts server api_versions and GET one

internal/service/alarms/internal/alertmanager/alertmanager_test.go, internal/service/cluster/collector/collector.go, internal/service/cluster/collector/collector_k8s.go, internal/service/cluster/db/repo/repository.go, internal/service/common/async/store.go, internal/service/common/clients/k8s/k8s.go, internal/service/common/db/models/data_source.go, internal/service/common/utils/persist.go, internal/service/resources/collector/collector.go, internal/service/resources/collector/collector_acm.go, internal/service/resources/collector/collector_k8s.go, internal/service/resources/db/repo/repository.go, internal/service/resources/serve.go
This adds the ability to watch for changes to ManagedCluster and Agent objects so that we can dynamically update our persistent storage rather than have to poll at fixed intervals.  The watch is implemented using a Reflector and supplying an adapter layer that receives cache update events and feeds them to the Collector which then updates our storage and emits async notification events to subscribers as needed.
=> CNF-16245: Add edge driven cluster updates with Reflector

internal/service/alarms/serve.go, internal/service/artifacts/serve.go, internal/service/cluster/serve.go, internal/service/common/api/errors.go, internal/service/common/api/middleware.go, internal/service/provisioning/serve.go, internal/service/resources/serve.go
This implements a workaround for a limitation of the http.ServeMux to convert plain text error responses to JSON.  The limitation is that it does not provide a means to specify whether error responses should be in plain text or JSON format.  The issue is discussed here [1].
The 'solution' is to wrap the ServeMux so that we supply a custom ResponseWriter that is capable of intercepting "text/plain" errors and re-format them to "application/problem+json" to comply with the ORAN interface specifications.
The previous approach attempted to better handle this scenario for a 404 error using a default "/" path, but overlooked that 405 errors are never returned as long as the "/" path is in the mux.
[1] https://github.com/golang/go/issues/65648
=> Intercept and convert plain text errors to JSON

internal/controllers/inventory_controller.go, internal/service/resources/collector/collector_k8s.go
Description:
- Add `secrets` to the resource-server clusterrole
- Expose errors coming from getting managed clusters
=> Resource server: add secrets to clusterrole and expose error

internal/service/cluster/db/repo/repository.go, internal/service/resources/db/repo/repository.go
When the resync ends and no data exists in the k8s API for some resource then the "NotIn" clause on the database query throws an error since the list passed to it is empty.  If no data exists in the API server then we simply want to delete ALL records therefore we don't need to supply a where clause.
=> Fix the end of sync query when not data is present

bundle/manifests/oran-o2ims-admin-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/oran-o2ims-maintainer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/oran-o2ims-provisioner-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/oran-o2ims-reader-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/oran-o2ims-subscriber-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, config/rbac/kustomization.yaml, config/rbac/o2ims.oran.openshift.io_inventories_editor_role.yaml, config/rbac/o2ims.oran.openshift.io_inventories_viewer_role.yaml, config/rbac/o2ims.provisioning.oran.org_clustertemplate_editor_role.yaml, config/rbac/o2ims.provisioning.oran.org_clustertemplate_viewer_role.yaml, config/rbac/o2ims.provisioning.oran.org_provisioningrequest_editor_role.yaml, config/rbac/o2ims.provisioning.oran.org_provisioningrequest_viewer_role.yaml, config/rbac/oran_o2ims_user_roles.yaml, config/testing/client-service-account-rbac.yaml
Defines function-specific RBAC roles for users of the O2IMS API and CRs. These roles can later be assigned to users or groups via ClusterRoleBindings.
The roles are defined for the following functions:
O2IMS API access:
+ reader: read-only access to all API endpoints
+ subscriber: read/write access to all subscription API endpoints
+ maintainer: read/write access to alarms and alarm configuration
+ provisioner: read/write access to templates and provisioning requests
+ admin: read/write access to all API endpoints
O2IMS CR access:
(note: these are mostly for developer testing since similar ones get
automatically created when our operator bundle is installed and run.)
+ editor: read/write access to corresponding CR
+ viewer: read-only access to corresponding CR
=> Define and package function-specific RBAC roles

internal/service/alarms/api/generated/alarms.generated.go, internal/service/alarms/api/openapi.yaml, internal/service/alarms/api/server.go
This is follow up of https://github.com/openshift-kni/oran-o2ims/pull/463 
Removing probableCause public endpoints as they are not defined yet. Will revisit this after spec is finalized.
=> remove probable cause endpoints from alarms server

api/inventory/v1alpha1/inventory_types.go, bundle/manifests/o2ims.oran.openshift.io_inventories.yaml, bundle/manifests/oran-o2ims-admin-binding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/oran-o2ims-maintainer-binding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/oran-o2ims-provisioner-binding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/oran-o2ims-reader-binding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/oran-o2ims-subscriber-binding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/crd/bases/o2ims.oran.openshift.io_inventories.yaml, config/manifests/bases/oran-o2ims.clusterserviceversion.yaml, config/rbac/kustomization.yaml, config/rbac/oran_o2ims_oauth_role_bindings.yaml, config/samples/v1alpha1_inventory.yaml, internal/controllers/inventory_controller.go, internal/controllers/inventory_controller_postgres.go, internal/controllers/inventory_controller_test.go, internal/controllers/utils/constants.go, internal/controllers/utils/types.go, internal/controllers/utils/utils.go, vendor/github.com/openshift-kni/oran-o2ims/api/inventory/v1alpha1/inventory_types.go
This configures the front-end kube-rbac-proxy instances to accept OIDC OAuth tokens rather than Kubernetes tokens.  Incoming tokens are verified by first validating their signature against the certificate downloaded from the configured OAuth server.  If the signature is
valid, then the user's roles are extracted from the token and used to
map to the Kubernetes RBAC roles to authorize the request.
Since our servers do inter-server communication and since they do not have OAuth tokens to exchange between themselves (not should they) we create separate kube-rbac-proxy instances that use the Kubernetes token validation to authorize their exchanges.
Therefore, any internal communications go through the "internal" proxy, and any public communications (e.g,. coming from the ingress controller) …
=> CNF-16478: Add OIDC validation at front-end proxies

api/provisioning/go.mod, api/provisioning/v1alpha1/provisioningrequest_validation.go, api/provisioning/v1alpha1/provisioningrequest_webhook.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_validation.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_webhook.go
Updates:
- Add validation for metadata name in the webhook to reject creation if its name is not a valid UUID. This aligns with the ProvisioningRequest REST API. 
- Refactor to use `webhook.CustomValidator` instead of `webhook.Validator` as the latter is deprecated.
=> CNF-16482: Validate metadata name as UUID and refactor to use CustomValidator

internal/service/common/db/postgres.go, internal/service/common/utils/repository.go, vendor/github.com/jackc/pgx/v5/tracelog/tracelog.go, vendor/modules.txt
- Pgx config is now explicit with additionally keep at least two connection alive 
- Enable pgx capability to get important debug info and capture any possible performance issues during DB interaction
e.g 
```
{"time":"2025-01-21T18:21:48.795474022Z","level":"INFO","source":{"function":"github.com/openshift-kni/oran-o2ims/internal/service/common/db.init.func1","file":"/workspace/internal/service/common/db/postgres.go","line":152},
"msg":"Database Query",
"event":"Query",
"duration":"26.711377ms",
"sql":"INSERT INTO alarm_definition (\"alarm_name\", \"alarm_last_change\", \"alarm_description\", \"proposed_repair_actions\", \"alarm_additional_fields\", \"alarm_dictionary_id\", \"severity\")\nVALUES ($1, $2, $3, $4, $5, $6, $7), ($8, $9, $10, $11, $12, $13, $14), ($15, $16, $17, $18, $19, …
```
=> Pgx explicit configs and enable trace capabilities

api/hardwaremanagement/v1alpha1/hardwaretemplate_types.go, api/hardwaremanagement/v1alpha1/node_pools.go, bundle/manifests/o2ims-hardwaremanagement.oran.openshift.io_hardwaretemplates.yaml, bundle/manifests/o2ims-hardwaremanagement.oran.openshift.io_nodepools.yaml, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/crd/bases/o2ims-hardwaremanagement.oran.openshift.io_hardwaretemplates.yaml, config/crd/bases/o2ims-hardwaremanagement.oran.openshift.io_nodepools.yaml, config/samples/v1alpha1_hardwaretemplate.yaml, vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/hardwaretemplate_types.go, vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/node_pools.go
Description:
- Add optional `resourceSelector` field to the `NodePoolData` structure used both in the `HardwareTemplate `CR and in the `NodePool` CR
- Make the `ResourcePoolId` field of the `NodePoolData` structure optional
Examples:
```console
apiVersion: o2ims-hardwaremanagement.oran.openshift.io/v1alpha1
kind: HardwareTemplate
metadata:
name: du-template-v1
namespace: oran-o2ims
spec:
bootInterfaceLabel: bootable-interface
extensions:
resourceTypeId: Resource-Group
hardwareProvisioningTimeout: 60m
hwMgrId: loopback-1
nodePoolData:
- hwProfile: profile-1-v1
name: master
resourcePoolId: master
resourceSelector: test              <<<<   New field
role: master
- hwProfile: profile-2-v1
name: worker
resourcePoolId: worker-pool
role: worker
status:
conditions:
- lastTransitionTime: …
```
=> Changes to hardware CRs

api/provisioning/v1alpha1/provisioningrequest_webhook.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_webhook.go
Once a ProvisioningRequest has been created, it's not allowed to change template reference unless the ProvisioningRequest has been fulfilled.
=> CNF-15632: Reject changes to templateName and templateVersion if not fulfilled

internal/controllers/inventory_controller.go, internal/service/common/notifier/event.go
In anticipation of inconsistencies between success return codes on the SMO API endpoints, and since we don't look for any response bodies, we are going to accept anything between 200 and 204 inclusively.
=> Loosen HTTP status code checks

bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/rbac/role.yaml, internal/cmd/operator/start_controller_manager.go, internal/controllers/provisioningrequest_clusterconfig.go, internal/controllers/provisioningrequest_clusterconfig_test.go, internal/controllers/provisioningrequest_controller.go, internal/controllers/provisioningrequest_controller_test.go, internal/controllers/suite_test.go, internal/controllers/utils/constants.go
Description:
- For a ManagedCluster and the corresponding Agent, add the `clustertemplates.o2ims.provisioning.oran.org/templateId` label with a value that points to `spec.TemplateId` of the ClusterTemplate used in the corresponding ProvisioningRequest.
- The above label is only added once a ProvisioningRequest becomes `fulfilled`.
- If the ProvisioningRequest goes through Day2 configuration and its status changes from `fulfilled`, the label is kept.
- The function that adds the labels is run during each reconciliation for which the ProvisioningRequest is `fulfilled` to ensure the label has the correct value, in the case it has been tempered with.
- Add tests.
=> Add ClusterTemplate ID as label in MCL and Agent CRs

internal/controllers/inventory_controller.go, internal/controllers/utils/constants.go
Since we only register once with the SMO it may be difficult/annoying for SMO developers to test their functionality.  With the following environment variable set to "true" we will redo the registration any time the Pod is restarted.
e.g., REGISTER_ON_RESTART=true
Any value that resolve to True with Go's strconv.ParseBool() will work.
=> Add env variable to control forced SMO registration

internal/controllers/provisioningrequest_clusterconfig.go, internal/controllers/provisioningrequest_clusterconfig_test.go
Add the expected label to all the `Agents` found in the managed cluster namespace + unit tests for this scenario.
Agents for a 3 node cluster:
```console
$ oc get agent -A
NAMESPACE   NAME    CLUSTER     APPROVED     ROLE     STAGE
cluster-1  <uuid>   cluster-1     true      master   Configuring
cluster-1  <uuid>   cluster-1     true      master   Configuring
cluster-1  <uuid>   cluster-1     true      master   Waiting for control plane
```
=> Handle artifacts labels for MNO

internal/service/cluster/api/server.go, internal/service/cluster/db/repo/repository.go
These new endpoints are defined in spec 8.0. It will be used by the alarm server to fetch the dictionaries
=> Implement alarm dictionary endpoints for cluster server

bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/manager/manager.yaml
Remove the limits for the O2IMS Deployment for now, to avoid OOMKilled situations.
The limits should be added back once their values are established.
=> Temporarily remove limits for the O2IMS deployment

api/provisioning/v1alpha1/provisioningrequest_types.go, bundle/manifests/o2ims.provisioning.oran.org_provisioningrequests.yaml, config/crd/bases/o2ims.provisioning.oran.org_provisioningrequests.yaml, internal/controllers/provisioningrequest_controller.go, internal/controllers/utils/conditions.go, internal/controllers/utils/utils.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_types.go
Introduced a new overall provisioning status `Pending`, which represents the CR validation and resource preparation phase. This status is set only when there are spec changes to the ProvisioningRequest. Any failed validation, resource rendering or generation result in the provisioning status to `Failed` which is same with current behavior.
`status.observedGeneration` has been introduced to differentiate whether the controller's reconcile was triggered by spec  changes or for other factors(watched resources or periodic requeues). It reflects the most recent generation observed by the controller and is updated to match metadata.generation during status updates to acknowledge the new generation.
The Pending status transition is quick. Tested the following scenarios:
- Invalid CR validation …
=> CNF-16275: Support pending status for ProvisioningRequest

README.md, internal/controllers/inventory_controller.go, internal/controllers/inventory_controller_test.go
The REGISTER_ON_RESTART env variable was meant to force a single registration on every Pod restart, but it was inadvertently causing a registration on every reconcile loop.  It was also noticed that when deploying from a bundle that it is not straightforward to set an env variable as it gets overridden automatically to align with the CSV, therefore, we are changing this to an annotation.
=> Fix debug mode handling for re-registration using an annotation

internal/service/alarms/api/generated/alarms.generated.go, internal/service/alarms/api/openapi.yaml, internal/service/common/api/middleware.go
v7 spec 
```
The Content-Type header shall be set to "application/merge-patch+json" according to IETF RFC 7396 [29].
```
/cc @alegacy 
/cc @klaskosk
=> only allow `merge-patch+json` for patch requests

Dockerfile
handles the warning 
```
4 warnings found (use --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 5)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 34)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 41)
```
=> remove FromAsCasing warning

internal/controllers/inventory_controller.go, internal/service/resources/collector/collector_hwmgr.go
This ensures that the default hwmgr plugin namespace is used even if the env variable is not set.
=> Fix lookup of hwmgr plugin namespace

internal/search/selector_evaluator.go, internal/search/selector_evaluator_test.go
The conformance tests pass in a search filter with an upper case UUID value so to pass the test we need to make our comparison case insensitive; at least for the 'eq' case.
=> Make UUID comparison case insensitive

.vscode/launch.json, internal/controllers/provisioningrequest_clusterconfig.go, internal/controllers/provisioningrequest_clusterconfig_test.go, internal/controllers/provisioningrequest_controller_test.go, internal/controllers/provisioningrequest_setup.go, internal/controllers/suite_test.go, internal/controllers/utils/constants.go
Description:
- add the following labels on the Agent CRs to enable the resource server:
`hardwaremanagers.hwmgr-plugin.oran.openshift.io/hwMgrId`
`hardwaremanagers.hwmgr-plugin.oran.openshift.io/hwMgrNodeId`
=> Add extra labels on the Agent CRs

internal/controllers/utils/utils.go, internal/service/cluster/collector/collector_k8s.go, internal/service/resources/collector/collector_hwmgr.go
* Link ClusterResource to Resource
This links the ClusterResource object to the Cluster object via the
ResourceID UUID value.  This depends on labels to be applied to the
Agent object so that we know which hwMgrID and hwMgrNodeID was used
to implement the node.   This labels will be provided in a separate
PR.
* Add labels to inventory resource
This adds the "labels" provided by the hardware manager as extensions
to the inventory resource object.
*  Include hwMgrId value in inventory uuid generation
We generate inventory UUID values based on the cloud id and the resource
name but the resource name does not necessarily have to be unique
across multiple hardware managers therefore we include the hwMgrId into
the string used to generate the UUID.
=> Include hwMgrId value in inventory uuid generation

internal/service/cluster/collector/collector.go
* Delete cluster resources on stale node cluster
At the end of init, the reflectors will report which NodeClusters
currently exist on the system.  We use that as a trigger to delete stale
NodeCluster objects, but when we do so, we don't first try to delete any
related ClusterResource objects.  That leads to a DB constraint
violation because of the FK relationship.
* Fix panic on duplicate node clusters in DB
We never expect that there will be multiple NodeCluster objects in the
database with the same name.  When we query for NodeCluster objects with
a specific name, we are returned an error indicating that multiple rows
were found when only one was expected.  This error is not handled, and
we dereference a nil pointer.
=> Fix side effects from duplicates

internal/search/selector_evaluator.go, internal/search/selector_evaluator_test.go, internal/service/alarms/serve.go, internal/service/artifacts/serve.go, internal/service/cluster/serve.go, internal/service/common/api/filtering.go, internal/service/common/api/filtering_test.go, internal/service/common/api/suite_test.go, internal/service/provisioning/serve.go, internal/service/resources/serve.go
The response from the http handler needs to be marshaled to a map of interface{} values so that it can be handled by the selector code.  The JSON decoder treats any numeric value as a float64, therefore, we need to change the selector evaluator to handle float64.
This wasn't needed in the original PoC implementation because the actual object type was passed to the selector rather than a map of interface{} values.  We cannot do that in this case because we only have the HTTP ResponseWriter with the marshaled output rather than the actual object type.
The behavior of the JSON marshaler is described here:
https://github.com/square/go-jose/pull/352
=> Fix selector number handling

internal/controllers/inventory_controller.go
The IMS endpoint points directly to the inventory API endpoints, but since we now support other API endpoints, this needs to be updated to be more generic.
=> Update IMS endpoint in O-Cloud registration

internal/service/alarms/serve.go, internal/service/artifacts/serve.go, internal/service/cluster/serve.go, internal/service/common/api/middleware/errors.go, internal/service/common/api/middleware/filtering.go, internal/service/common/api/middleware/filtering_test.go, internal/service/common/api/middleware/middleware.go, internal/service/common/api/middleware/middleware_suite_test.go, internal/service/common/api/utils.go, internal/service/provisioning/serve.go, internal/service/resources/serve.go
Changes applicable for all servers: 
- New middleware to allow for trailing slash. i.e `/alarms` and `/alarms/` are now both valid
- Refactoring existing middleware to align them further.
=> allow trailing slash and middleware refactoring for all servers

internal/controllers/provisioningrequest_clusterinstall.go, internal/controllers/provisioningrequest_clusterinstall_test.go, internal/controllers/utils/conditions.go
A workaround to add the `import.open-cluster-management.io/disable-auto-import annotation` to ManagedCluster via the rendered ClusterInstance's `spec.ExtraAnnotations.ManagedCluster`. The annotation temporarily disables auto-import for ManagedCluster when it gets created. This update is to prevent a race condition where stale cluster might be re-imported because timing issues. The annotation is removed from ManagedCluster once the cluster installation process begins.
This also includes a fix to update `provisioningStatus.updateTime` only when `provisioningStatus.provisioningPhase` or `provisioningStatus.provisioningDetails` is changed.
=> Add disable-auto-import annotation to prevent stale ManagedCluster re-imported

internal/controllers/provisioningrequest_hwprovision.go
Since the `Pending` status was introduced (which is the initial status for a new generation), it’s impossible for this fulfilled check to pass during hardware template updates. Given that webhook validation has been added to reject updates to the referenced template if it’s not fulfilled, we should be able to safely remove this obsolete check.
=> Remove fulfilled check for hwTemplate changes

docs/samples/git-setup/clustertemplates/version_4.Y.Z+1/sno-ran-du/clusterinstance-defaults-v1.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v1.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v2.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v3.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v4.yaml, docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-full-du/clusterinstance-defaults-full-du-v1.yaml
If the prefered method to enable siteconfig operator is through the command 
`oc patch multiclusterhubs.operator.open-cluster-management.io multiclusterhub -n <ACM_NAMESPACE> --type json --patch '[{"op": "add", "path":"/spec/overrides/components/-", "value": {"name":"siteconfig","enabled": true}}]'`
, then the default namespace of siteconfig operator will be open-cluster-management. 
This PR is to update the namespace to open-cluster-management in the samples in order to avoid confusion.
=> update siteconfig operator namespace to open-cluster-management in the sample CRs

internal/service/cluster/collector/collector_alarms.go
{"time":"2025-02-07T14:59:31.862941086Z","level":"ERROR","source":{"function":"github.com/openshift-kni/oran-o2ims/internal/service/cluster/collector.(*AlarmsDataSource).buildAlarmDictionaryIDToAlarmDefinitions","file":"/workspace/internal/service/cluster/collector/collector_alarms.go","line":292},"msg":"no alarm dictionary ID found for node cluster type","NodeClusterType ID":"14ec7a85-8304-5455-a597-0770e46dcb20"}
{"time":"2025-02-07T14:59:31.863104628Z","level":"ERROR","source":{"function":"github.com/openshift-kni/oran-o2ims/internal/service/cluster/collector.(*AlarmsDataSource).makeAlarmDictionaries","file":"/workspace/internal/service/cluster/collector/collector_alarms.go","line":393},"msg":"no alarm dictionary ID found for node cluster type","NodeClusterType …
=> fix cluster server assertion error

.vscode/launch.json, internal/controllers/inventory_controller.go, internal/service/artifacts/api/generated/artifacts.generated.go, internal/service/artifacts/api/openapi.yaml, internal/service/artifacts/api/server.go
This PR exposes the default values as they are found in the ConfigMaps.
Part 2 will address separating the immutable and editable values.
Example:
```console
$curl -X GET \
-s -k -H 'Content-Type: application/json' \
-H "Authorization: Bearer $MY_TOKEN" \
"$BASE_URL/o2ims-infrastructureArtifacts/v1/managedInfrastructureTemplates/sno-ran-du.v4-17-3-1/defaults" | jq 
{
"clusterInstanceDefaults": {
...
"nodes": [
...
],
"templateRefs": [
{
"name": "ai-cluster-templates-v1",
"namespace": "siteconfig-operator"
}
]
},
"policyTemplateDefaults": {
"cluster-log-fwd-filters-labels": "{\"label1\": \"test1\", \"label2\": \"test2\"}",
...
"sriov-network-vlan-2": "111",
}
}
```
=> Artifacts server: Expose cluster provisioning default values - part 1

internal/service/alarms/internal/infrastructure/clusterserver.go, internal/service/alarms/internal/infrastructure/infrastructure.go
This prevents the alarm server to restart when the cluster server is not yet up
=> Move first fetch all operation inside sync routine

README.md, api/inventory/v1alpha1/inventory_types.go, bundle/manifests/o2ims.oran.openshift.io_inventories.yaml, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/crd/bases/o2ims.oran.openshift.io_inventories.yaml, config/manifests/bases/oran-o2ims.clusterserviceversion.yaml, internal/controllers/inventory_controller.go, internal/controllers/utils/constants.go, internal/controllers/utils/utils.go, vendor/github.com/openshift-kni/oran-o2ims/api/inventory/v1alpha1/inventory_types.go
To better align with how trust bundles are created and used in other parts of the system, the name of the expected file is being changed from ca-bundle.pem to ca-bundle.crt.  OpenShift is inconsistent in how it expects this file to be named in other areas. But, in the injected trust bundle case, and in the cluster proxy case, the file is expected to be ca-bundle.crt so we are aligning to that.
Beware that when providing a set of trusted client CA certificates to the ingress controller, it is expected to be ca-bundle.pem.
=> Update trust bundle procedure and naming

internal/service/cluster/collector/collector.go, internal/service/cluster/collector/collector_k8s.go, internal/service/resources/collector/collector.go, internal/service/resources/collector/collector_k8s.go
This updates the cluster server so that the local-cluster is included as a NodeCluster object for tracking alarms against it. A DeploymentManager will not be created for it since; at this time, it is not expected that the SMO will need to run workloads on the hub.
=> Include local-cluster as NodeCluster without extra label

api/provisioning/v1alpha1/provisioningrequest_webhook.go, api/provisioning/v1alpha1/provisioningrequest_webhook_test.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_webhook.go
We should allow template reference updates if the ProvisioningRequest fails due to an allowed error, such as validation, rendering, or resource creation failures.
For example, if hardware has already been provisioned and the ProvisioningRequest is updated to a new template for hardware configuration, but the new template is invalid and causes hardware template rendering to fail, the user should be able to revert to the previous template or switch to another one.
=> CNF-16511: Loosen the validation check for fulfilled state

.vscode/launch.json, internal/controllers/provisioningrequest_clusterinstall.go, internal/controllers/provisioningrequest_controller_test.go
The disable-auto-import annotation is added to the ManagedCluster when it is created and removed once installation starts to prevent a race condition, as implemented in [PR #546](https://github.com/openshift-kni/oran-o2ims/pull/546). However, it turns out that removing the annotation at this stage is too early. At that point, the cluster has only just started installation and the race condition may still occur. This updates to remove the annotation only after the cluster installation has been completed.
=> Remove disable-auto-import annotation after the installation is complete

README.md, api/inventory/v1alpha1/inventory_types.go, bundle/manifests/o2ims.oran.openshift.io_inventories.yaml, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/crd/bases/o2ims.oran.openshift.io_inventories.yaml, config/manifests/bases/oran-o2ims.clusterserviceversion.yaml, internal/controllers/utils/utils.go, internal/service/common/auth/auth_oauth.go, internal/service/common/auth/auth_rfc8705.go, internal/service/common/auth/auth_rfc8705_test.go, internal/service/common/auth/middleware.go, internal/service/common/utils/config.go, vendor/github.com/openshift-kni/oran-o2ims/api/inventory/v1alpha1/inventory_types.go
This adds support for client certificate bound access tokens (e.g., RFC8705).  When this feature is enabled on the authorization server each token generated contains an attribute which represents the SHA256 fingerprint of the TLS certificate which was used by the client who requested the token.
When this attribute is added to the token, Resource Servers are supposed to validate that the token is only used by a client presenting that same TLS certificate.  This is verified by comparing the fingerprint contained within the token with the fingerprint of the certificate being used to make the request.
We only support being behind an ingress proxy; therefore, we never expect TLS to be terminated directly on each server for OAuth use cases. For this reason, we only expect to get the client …
=> CNF-16878: Add client certificate binding support (RFC8705)

.vscode/launch.json, api/provisioning/v1alpha1/provisioningrequest_validation.go, api/provisioning/v1alpha1/provisioningrquest_validation_test.go, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/rbac/role.yaml, go.mod, internal/cmd/operator/start_controller_manager.go, internal/controllers/clustertemplate_controller.go, internal/controllers/clustertemplate_controller_test.go, internal/controllers/provisioningrequest_clusterconfig_test.go, internal/controllers/provisioningrequest_resourcecreation.go, internal/controllers/suite_test.go, internal/controllers/utils/constants.go, internal/controllers/utils/provision.go, internal/controllers/utils/provision_test.go, internal/controllers/utils/test_common.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_validation.go
Steps:
- obtain the ClusterInstance CRD and get the schema for the CRD version that is stored and served
- from the schema obtained above, remove all the `required` properties since the ClusterInstance default ConfigMap will probably not contain all the required configuration.
- from the ClusterInstance default ConfigMap, remove the `label` property for each node interface as that is not part of the ClusterInstance schema, but a mechanism used by the O-Cloud Manager for provisioning
- validate the ConfigMap content against the CRD schema using the existing `ValidateJsonAgainstJsonSchema`  function
Updated existing unit tests and added more for the extra functionality.
=> CNF-16737: Validate the ClusterInstance defaults ConfigMap against the ClusterInstance CRD schema

api/provisioning/v1alpha1/conditions.go, api/provisioning/v1alpha1/provisioningrequest_validation.go, api/provisioning/v1alpha1/provisioningrequest_webhook.go, internal/controllers/provisioningrequest_controller.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/conditions.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_validation.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_webhook.go
Updates:
- Removed the transition from failed to progressing. The system cannot autonomously recover from fatal errors. It requires either a PR update or delete/recreate to get rid of the error.
- Moved the preparation steps into a separate function to reduce the complexity of `run` function.
=> Remove transition from failed to progressing

api/provisioning/v1alpha1/provisioningrequest_validation.go, api/provisioning/v1alpha1/provisioningrequest_webhook.go, internal/controllers/provisioningrequest_clusterinstall.go, internal/controllers/provisioningrequest_clusterinstall_test.go, internal/controllers/provisioningrequest_controller_test.go, internal/controllers/utils/conditions.go, internal/controllers/utils/provision_test.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_validation.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_webhook.go
Siteconfig has introduced validation check in ACM 2.13+ that rejects any spec updates during cluster installation. This update aligns with that validation. 
Updates:
- ProvisioningRequest webhook and controller validation updates have been updated to disallow any updates during installation.
- The defaults set in the ClusterInstance CRD will be applied to the rendered ClusterInstance after dry-run, so run dry-run before checking ClusterInstance changes in the controller. If we start requiring ACM 2.13+, we could remove our post provisioning updates check and instead leverage the validation in the siteconfig.
- To pass the dry-run for the spec updates that caused by IMS:
- Extract nodeInfo(e.g. bmc and macAddress that were from hw manager) from the existing ClusterInstance and merge it …
=> Align with the ClusterInstance validation check introduced in ACM 2.13

docs/enhancements/infrastructure-monitoring-service-api/alarms.md
This enhancement talks about re-architecting the Alarm server as specified in `InfrastructureMonitoring Service API` o-ran spec. 
Notable changes include: 
- Data returned from API calls follow closely to what's defined by o-ran 
- Dynamically checking and gathering cluster resources during init such as PrometheuseRule
- Combining servers into the same code base 
- Introducing persistence storage via Postgres
This enhancement includes all the code tested during spike, the k8s resources needed to deploy through operator and other libraries/tool that can be used to quickly develop this.
co-authored with @browsell and @Jennifer-chen-rh
=> CNF-13185: Enhancement for alarms

internal/service/common/async/store.go
Fixes a panic caused by not breaking out of main loop which leads to closing an already closed channel on shutdown.
=> Fix panic on shutdown

internal/service/cluster/collector/collector.go
ClusterResources can/do appear before their NodeCluster.  When this happens, we log the condition and later link the two objects when the NodeCluster appears.  When the log is generated, the async event handling should not continue.  If it does, a panic occurs.
=> Fix panic on cluster provisioning

api/hardwaremanagement/v1alpha1/node.go, bundle/manifests/o2ims-hardwaremanagement.oran.openshift.io_nodes.yaml, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/crd/bases/o2ims-hardwaremanagement.oran.openshift.io_nodes.yaml, config/manifests/bases/oran-o2ims.clusterserviceversion.yaml, internal/controllers/provisioningrequest_clusterinstall.go, internal/controllers/provisioningrequest_clusterinstall_test.go, internal/controllers/provisioningrequest_controller.go, internal/controllers/provisioningrequest_hwprovision.go, internal/controllers/provisioningrequest_hwprovision_test.go, internal/controllers/utils/constants.go, internal/controllers/utils/hardware_utils.go, internal/controllers/utils/provision.go, internal/controllers/utils/types.go, vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/node.go
This pull request adds support for cluster provisioning with the Metal3 plugin by utilizing the newly introduced hostRef field in the Cluster instance object. The hostRef field enables the creation of Bare Metal Hosts (BMH) and other node-level installation resources—such as InfraEnv and NMStateConfig—within the BMH namespace. It leverages the unstructured site-config cluster instance to eliminate dependencies on upgrading the siteconfig package.
As a result of this change, the pull secret must now be available in the BMH namespace. The current logic that copies the pull secret from the template namespace to the cluster namespace will be deprecated.
Additionally, this update introduces a new field in the Node object. The plugin will utilize this new field to determine and return the BMH …
=> CNF-17204: Enable Cluster Provisioning with metal3 plugin

.konflux/Dockerfile, .konflux/Dockerfile.bundle, .konflux/overlay/map_images.in.yaml, .konflux/overlay/overlay.bash, .konflux/overlay/pin_images.in.yaml
1. Introduce the bundle Dockerfile.
2. Introduce 'overlay.bash' for the csv overlay.
'overlay.bash' is able to pin csv images (sha256) , add the 'relatedImages' csv section and optionally map the images to staging/production registries. These functionalites are based on yaml files passed as input parameters as described [here](https://github.com/openshift-kni/oran-o2ims/pull/643/files#diff-a2a5613307884c264df5f374b659888c01c346426dad31be8fea6bbdd8ec677fR317). Will make all the overlay, including this [logic](https://github.com/openshift-kni/oran-o2ims/pull/643/files#diff-a2a5613307884c264df5f374b659888c01c346426dad31be8fea6bbdd8ec677fR267) completely configurable in posterior commits not to hardcode release data as part of the script itself.
The script will be invoked when building the …
=> introduce the konflux overlay

api/provisioning/v1alpha1/provisioningrequest_validation.go, api/provisioning/v1alpha1/provisioningrequest_webhook.go, api/provisioning/v1alpha1/provisioningrequest_webhook_test.go, internal/controllers/provisioningrequest_controller.go, internal/controllers/utils/conditions.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_validation.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_webhook.go
Remove the restriction since templateName and templateVersion are no longer invariant and we expect user updates to solve issues.
=> Remove webhook restriction on templateName and templateVersion updates

go.mod, internal/controllers/utils/utils.go, internal/service/common/api/utils.go, internal/service/common/api/utils_test.go, internal/service/common/notifier/notifier_worker.go, internal/service/common/notifier/provider.go
This PR refactors the client provider to use `authType` when serving new clients from the ClientFactory.
/cc @alegacy @browsell
=> Refactor client provider to use authType

bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/rbac/role.yaml, hwmgr-plugins/controller/hardwareplugin_controller.go, internal/controllers/hardwareplugin_manager_setup.go, internal/controllers/inventory_controller.go, internal/controllers/utils/constants.go
This PR introduces the registration validation process for onboarding new `HardwarePlugins`. It includes logic to verify that the `apiRoot` of the HardwarePlugin server is accessible.
/cc @browsell @alegacy
=> Add validation logic when registering a new HardwarePlugin

config/manager/manager.yaml
Replaced the postgresql image with one that is publicly available in order to avoid requiring a pull secret in deployment automation being contributed to the ORAN-SC community.
=> nonproduction: Update manager config to use postgresql-16-c9s image

internal/cmd/operator/start_controller_manager.go, internal/controllers/inventory_controller.go, internal/controllers/provisioningrequest_clusterconfig.go, internal/controllers/utils/hardware_utils.go
This PR enhances the post-provisioning process by refining the application of the host node ID label to the `Agent` object. It ensures accurate matching of the `BareMetalHost` resource with the specified `hostname`, while also improving support for non-Metal3 hardware plugins, thereby increasing reliability and flexibility in node identification.
/cc @browsell @donpenney @alegacy @tliu2021
=> Improve how the host node ID label is applied to an agent post provisioning

hwmgr-plugins/controller/utils/allocated_node.go, hwmgr-plugins/metal3/controller/inventory.go, hwmgr-plugins/metal3/server/inventory_server.go, internal/service/cluster/collector/collector.go, internal/service/resources/collector/collector.go
This update includes the following:
- Fix metal3 resource pool reporting so all pools are returned
- Add additional info to metal3 resource query, with annotations to support adding details to the BMH
- Reduce inventory polling interval to 1 minute from 10
=> metal3: Update inventory reporting

bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/manager/manager.yaml, internal/controllers/inventory_controller.go, internal/controllers/inventory_controller_postgres.go, internal/controllers/provisioningrequest_controller.go, internal/controllers/provisioningrequest_upgrade.go, internal/service/alarms/internal/serviceconfig/serviceconfig.go
- Update PR reconciler to requeue when ClusterProvision condition is not yet present
- Change recurrent inventory reconciler logs to Debug to eliminate flood of logs every 5 minutes
- Add app label to controller-manager and alarms-server-events-cleanup pods to get rid of warning in controller-manager logs
=> Update PR reconciler to requeue when ClusterProvision condition is not yet present

hwmgr-plugins/api/server/provisioning/server.go, hwmgr-plugins/controller/utils/allocated_node.go, hwmgr-plugins/metal3/cmd/start_metal3plugin_server.go, hwmgr-plugins/metal3/controller/baremetalhost_manager.go, hwmgr-plugins/metal3/controller/helpers.go, hwmgr-plugins/metal3/controller/inventory.go, hwmgr-plugins/metal3/controller/metal3_allocatednode_controller.go, hwmgr-plugins/metal3/controller/metal3_hardwareplugin_setup.go, hwmgr-plugins/metal3/controller/metal3_nodeallocationrequest_controller.go
This update introduces a reconcile hook on AllocatedNode deletion that initiates deprovisioning of the associated BMH.
Additionally, it ensures that the corresponding NodeAllocationRequest is deleted once all its child AllocatedNode resources are removed.
The deletion uses the DeletePropagationForeground policy to guarantee that all dependent resources are fully cleaned up before the NodeAllocationRequest itself is deleted.
=> CNF-18183:: Added BMH deprovisioning on AllocatedNode deletion

api/provisioning/v1alpha1/provisioningrequest_webhook.go, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/webhook/manifests.yaml, hwmgr-plugins/metal3/controller/baremetalhost_manager.go, hwmgr-plugins/metal3/controller/helpers.go, hwmgr-plugins/metal3/controller/metal3_allocatednode_controller.go, vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_webhook.go
When a node is deleted, the deallocation hook powers off the host as part
of the deprovisioning process. However, if a BIOS firmware update job
is still in progress at the time of deletion, the job may get stuck,
preventing the BMH from transitioning to the Available state.
This update ensures the host is powered off only after deprovisioning is
complete and the BMH has reached the Available state, allowing any pending
jobs to finish successfully. This behavior applies only if the BMH has not
been provisioned.
To protect provisioned hosts, deletion of a ProvisionRequest in the
Configuration In Progress state (i.e., after the host has been provisioned)
will now be blocked by a validating webhook.
=> Wait for BMH to become Available before powering off the host

hwmgr-plugins/controller/utils/allocated_node.go, hwmgr-plugins/controller/utils/allocated_node_test.go, hwmgr-plugins/metal3/controller/helpers.go
Changed `GenerateNodeName()` from returning a random UUID to a deterministic function that takes parameters (pluginID, clusterID, bmhNamespace, bmhName).
Assisted-by: Cursor and claude-4-sonnet
/cc @donpenney @browsell
=> Implement deterministic AllocatedNode naming with K8s RFC 1123 compliance

hwmgr-plugins/metal3/controller/baremetalhost_manager.go, hwmgr-plugins/metal3/controller/baremetalhost_manager_test.go, hwmgr-plugins/metal3/controller/helpers.go, internal/controllers/provisioningrequest_controller.go, internal/controllers/utils/conditions.go, internal/controllers/utils/utils_test.go
This update improves the handling when there are multiple nodes with the same resource selector labels matching a NodeAllocationRequest. It also ensures the networkData is cleared properly in the case where there are day0 updates during provisioning.
In addition, Cursor was used to update test code, including adding some coverage for recent updates.
Assisted-by: Cursor/claude-4-sonnet
=> OCPBUGS-60633: Improve handling for multiple node matches

hwmgr-plugins/metal3/controller/baremetalhost_manager.go, hwmgr-plugins/metal3/controller/baremetalhost_manager_test.go, hwmgr-plugins/metal3/controller/helpers.go
The temporary node-name BMH annotation used by the metal3 plugin can result in reuse of a stale name, so is being removed.
=> metal3: Drop temporary node-name annotation

docs/dev/env_acm.md, internal/service/alarms/api/server.go, internal/service/alarms/internal/alertmanager/api.go, internal/service/alarms/internal/alertmanager/api_test.go, internal/service/alarms/serve.go
address [this](https://github.com/openshift-kni/oran-o2ims/pull/820#discussion_r2260552105). Follows the official way https://github.com/prometheus/alertmanager 
/cc @donpenney
=> replace 'alertManager' with 'alertmanager' for consistent naming

Makefile, hwmgr-plugins/metal3/controller/helpers_test.go, hwmgr-plugins/metal3/server/inventory_server_test.go, hwmgr-plugins/metal3/server/serve_test.go
Fix two separate issues causing the Metal3 Server test suite to hang indefinitely in CI:
1. **Race condition in concurrent goroutine test**: The inventory server thread safety test was sharing mock clients across goroutines, causing deadlocks when gomock objects were accessed concurrently. Fixed by creating individual mock clients per goroutine and adding timeout protection.
2. **Environment-dependent server startup behavior**: Tests expected auth.GetAuthenticator() to fail in non-Kubernetes environments, but CI unexpectedly has Kubernetes access, causing the server to actually start and hang indefinitely. Fixed by adding 5-second timeouts to all Serve() calls and flexible assertions that handle both local failure and CI timeout scenarios.
Root cause: CI environment has Kubernetes context …
=> fix(metal3/server): resolve CI timeout issues in server test suite

hwmgr-plugins/metal3/controller/baremetalhost_manager.go, hwmgr-plugins/metal3/controller/baremetalhost_manager_test.go, hwmgr-plugins/metal3/controller/helpers.go, hwmgr-plugins/metal3/controller/resource_selection.go, hwmgr-plugins/metal3/controller/resource_selection_test.go
This update moves resource selection logic into its own resource_selection.go module, with primary and secondary filtering.
The primary filtering parses the resource selection criteria to get any specified label references, which are then used to generate a List filter for the initial BMH query when fetching the list of available nodes. The resulting BMH list is then passed through the new secondary filter, which checks applicable criteria against the corresponding HardwareData CR.
Key features:
- Two-stage filtering architecture (primary/secondary filters)
- Hardware data criteria matching with configurable case sensitivity
- Support for string/integer operators (==, !=, >, <, >=, <=, ~, !~)
- Advanced device filtering for NICs and storage with complex qualifiers
Assisted-by: Claude …
=> CNF-18815: metal3: Add hardwaredata resource selector support

hwmgr-plugins/metal3/controller/baremetalhost_manager.go, internal/controllers/provisioningrequest_hwprovision.go, internal/controllers/utils/utils.go
- Clear PR callback annotations after hardware provisioning status is processed
- Clear config-in-progress annotation when node fails in processBMHUpdateCase()
- Prevent stale callback annotations from causing false callback detection in future reconciliations
Assisted-by: Cursor/claude-4-sonnet
=> Clear callback annotations after hardware provisioning status is processed

docs/cluster-provisioning.md, internal/controllers/provisioningrequest_clusterinstall.go, internal/controllers/utils/conditions.go
This PR refactors ProvisioningRequest upgrade handling by moving upgrade transformations to the buildClusterInstance phase and removing redundant validation logic now handled by the SiteConfig Operator’s ClusterInstance admission webhook (introduced in ACM 2.13+). It also updates the minimum ACM version requirement to 2.14+.
/cc @browsell @donpenney
=> Refactor ProvisioningRequest upgrade handling and remove redundant validation

hwmgr-plugins/api/server/nar-callback/server.go, internal/controllers/provisioningrequest_clusterinstall.go, internal/controllers/provisioningrequest_controller.go, internal/controllers/provisioningrequest_hwprovision.go, internal/controllers/utils/utils.go, test/e2e/e2e_suite_test.go
This commit fixes several issues in the hardware provisioning workflow to improve reliability.
1. Improves callback deduplication: Prevents the server from incorrectly filtering out necessary "InProgress" callbacks, ensuring timely status updates are processed correctly.
2. Corrects timeout detection: The timeout check is now only skipped for final states (Succeeded, Failed, TimedOut), ensuring that provisioning timeouts are properly detected.
3. Fixes callback annotation persistence: Ensures that when callback annotations are cleared, the change is saved correctly. This prevents false callback detections in subsequent reconciliations.
4. Initialize the ClusterInstanceProcessed, ClusterProvisioned, and HardwareProvisioned conditions with a status of False and a reason of InProgress …
=> OCPBUGS-61950 / OCPBUGS-62072: Resolve hardware provisioning callback and timeout detection issues

api/hardwaremanagement/v1alpha1/hardwareprofile_types.go, api/hardwaremanagement/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/clcm.openshift.io_hardwareprofiles.yaml, bundle/manifests/oran-o2ims.clusterserviceversion.yaml, config/crd/bases/clcm.openshift.io_hardwareprofiles.yaml, config/manifests/bases/oran-o2ims.clusterserviceversion.yaml, hwmgr-plugins/metal3/controller/helpers.go, hwmgr-plugins/metal3/controller/helpers_test.go, hwmgr-plugins/metal3/controller/hostfirmwarecomponents_manager.go, hwmgr-plugins/metal3/controller/hostfirmwarecomponents_manager_test.go
The SimpleUpdate API does not take a device id as a parameter. It is passed a URL to an image, the BMC will consume that image and apply it to all applicable devices. 
This PR removed the slot/location identifier associated with each image, now the hardware profile will just specify a list of image versions and URLs.
nicFirmware:
- url:  <>
version: 0.0.0.0
- url: <>
version: 1.1.1.1
Generated-By: Cursor/claude-4-sonnet
=> Remove slot from nic f/w schema

internal/controllers/provisioningrequest_controller.go, internal/controllers/provisioningrequest_controller_test.go, internal/controllers/provisioningrequest_hwprovision.go, internal/controllers/utils/hardware_utils.go, internal/controllers/utils/hardware_utils_test.go
This PR propagates the failed condition status with the corresponding error message to the provisioningState and provisioningDetails.
Problem: ProvisioningRequests would get stuck in a progressing state during hardware provisioning failures because the failure detection logic wasn't properly checking hardware-specific conditions.
Solution: Enhanced the condition failure detection to include hardware provisioning and configuration conditions, and improved the logic to only treat conditions as failed when they have explicit Failed or TimedOut reasons. Additionally, added reason mapping between hardware management conditions and provisioning request conditions to ensure consistent state transitions across all failure scenarios.
ℹ️ Assisted-by: Cursor and claude-4-sonnet
Resolves: …
=> OCPBUGS-61948: Propagate failed condition status to provisioning state and detail
