openshift-kni/oran-o2ims

docs/dev/env.md

Added a documentation for 'Setup development environment'.

MGMT-16146: Added a doc for setup dev env

---

docs/dev/env.md

Updated 'Create parameters yaml' section:
* s/pull_secret/pullsecret
* Added a note about 'pool' and 'pullsecret' attributes.

docs: update dev env instructions

---

docs/dev/env.md

Added more details to 'Operators configuration' section.

Updates to env.md

---

internal/openapi/spec.yaml

* Added resource endpoints (resourceTypes/resourcePools/resources) to the OpenAPI spec.
* Added a makefile target for validting the spec.yaml file.

MGMT-16410: OpenAPI spec - added resource endpoints

---

README.md

Update the README.md file with details about the Resource server.

MGMT-16357: Resource server - update readme

---

.containerignore
Dockerfile
Makefile
cmd/main.go
config/manager/kustomization.yaml
config/rbac/role.yaml
internal/controllers/orano2ims_controller.go
internal/controllers/suite_test.go

Description:
- Update the RBAC rules to account for all the resources the operator needs to handle
- Update the Makefile, Dockerfile and .containerignore for enabling the build of the operator image

MGMT-16144 - Operator - Fix make deploy and RBAC

---

.containerignore
Makefile
bundle.Dockerfile
bundle/manifests/oran-o2ims-controller-manager-metrics-service_v1_service.yaml
bundle/manifests/oran-o2ims-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/oran-o2ims.clusterserviceversion.yaml
bundle/manifests/oran.openshift.io_orano2imses.yaml
bundle/metadata/annotations.yaml
bundle/tests/scorecard/config.yaml
config/crd/kustomization.yaml
config/manager/kustomization.yaml
config/manifests/bases/oran-o2ims.clusterserviceversion.yaml
config/manifests/kustomization.yaml
config/scorecard/bases/config.yaml
config/scorecard/kustomization.yaml
config/scorecard/patches/basic.config.yaml
config/scorecard/patches/olm.config.yaml

Description:
- add the needed files to build the operator bundle

MGMT-16144: Add operator bundle

---

docs/dev/env_devscripts.md

Update 'env_devscripts' document.

docs: update env_devscripts

---

internal/cmd/server/start_resource_server.go
internal/service/deployment_manager_handler.go
internal/service/resource_fetcher.go
internal/service/resource_handler.go
internal/service/resource_pool_fetcher.go
internal/service/resource_pool_handler.go
internal/service/resource_type_handler.go

Fixed some typos and wrong func signature descriptions.

NO-ISSUE: fixed typos and comments

---

docs/dev/env_acm.md

Else yaml apply fails with an excepted: namespaces "mgmt-spoke1" not found.

Mention that namespaces should be created first

---

README.md

Readme update for alarm subscription server

Add alarm subscription readme

---

api/v1alpha1/clusterrequest_types.go
config/crd/bases/oran.openshift.io_clusterrequests.yaml

Description:
- add the clusterTemplateRef and clusterTemplateInput to the ClusterRequest CRD to avoid future merge conflicts

CNF-13446: ClusterRequest CRD fields

---

internal/service/alarm_definition_handler.go
internal/service/alarm_handler.go
internal/service/alarm_probable_cause_handler.go
internal/service/resource_handler.go
internal/service/resource_pool_handler.go
internal/service/resource_type_handler.go

Removed unsed `jsonAPI` from handlers (can be added ad-hoc when needed).

NO-ISSUE: remove redundant jsonAPI from handlers

---

config/samples/oran.openshift.io_v1alpha1_clusterrequest.yaml
config/samples/oran.openshift.io_v1alpha1_clustertemplate.yaml
internal/controllers/clusterrequest_controller.go
internal/controllers/utils/constants.go
internal/controllers/utils/utils.go
internal/controllers/utils/utils_test.go
internal/files/controllers/clusterinstance-template.yaml

- Implement deep merge function for maps and deep indexing merge function for slices
- Add more detailed logs and a bit restructuring
- Update sample clustertemplate with latest clusterinstance schema for testing
/cc @irinamihai @bartwensley

CNF-13526: Ensure the accurate merging of clusterTemplateInput with the default data

---

docs/samples/policyTemplateSchema.yaml

Description:
- sample for ACM policy generator that would be used in the ClusterTemplate spec.inputDataSchema.policyTemplateSchema
- the current sample is subject to change

CNF-13706: [POC2] ACM PolicyGenerator Schema

---

internal/service/subscription_handler_test.go

In the current k8s dependencies, the fake client does not support server-side apply calls and returns an error in the ginkgo tests:
```
[FAILED] Unexpected error:
<*errors.errorString | 0xc00064e1a0>:
apply patches are not supported in the fake client. Follow https://github.com/kubernetes/kubernetes/issues/115598 for the current status
{
s: "apply patches are not supported in the fake client. Follow https://github.com/kubernetes/kubernetes/issues/115598 for the current status",
}
occurred
```
This update adds a check for this error to bypass the failure, until the k8s modules can be updated to a version that does not produce this error.

NO-ISSUE: test: Avoid fake client server-side apply error

---

.golangci.yml
internal/controllers/orano2ims_controller.go

Enables the code complexity test and addresses the violations reported by the golintci tool.

CNF-13956: Enable gocyclo linter configuration

---

.golangci.yml
internal/cmd/operator/start_controller_manager.go
internal/cmd/server/start_alarm_notification_server.go
internal/cmd/server/start_alarm_subscription_server.go
internal/controllers/clusterrequest_controller.go
internal/controllers/clustertemplate_controller.go
internal/controllers/utils/utils.go
internal/jq/query.go
internal/jq/tool.go
internal/logging/logger.go
internal/metrics/path_tree.go
internal/persiststorage/persiststorage.go
internal/persiststorage/persiststorage_configmap.go
internal/search/paths_lexer.go
internal/search/selector_lexer.go
internal/service/adapter.go
internal/service/alarm_handler.go
internal/service/alarm_mapper.go
internal/service/alarm_notification_dispatcher.go
internal/service/alarm_notification_handler.go
internal/service/alarm_notification_searcher.go
internal/service/constants.go
internal/service/resource_fetcher.go
internal/service/resource_handler.go
internal/service/resource_type_handler.go
internal/service/subscription_handler.go
internal/text/dedent.go

This update addresses a variety of issues identified by the golangci-lint gocritic test.

CNF-13955: Enable golangci-lint gocritic test

---

.golangci.yml
.vscode/launch.json
README.md
internal/authentication/flags.go
internal/authentication/handler_wrapper.go
internal/authentication/handler_wrapper_test.go
internal/cmd/server/start_alarm_notification_server.go
internal/cmd/server/start_alarm_server.go
internal/cmd/server/start_alarm_subscription_server.go
internal/cmd/server/start_deployment_manager_server.go
internal/cmd/server/start_infrastructure_inventory_subscription_server.go
internal/cmd/server/start_metadata_server.go
internal/cmd/server/start_resource_server.go
internal/controllers/clusterrequest_controller.go
internal/controllers/utils/constants.go
internal/controllers/utils/utils.go
internal/network/listener.go
internal/network/listener_test.go
internal/service/alarm_fetcher.go
internal/service/alarm_handler.go
internal/service/alarm_notification_searcher.go
internal/service/deployment_manager_handler.go
internal/service/resource_fetcher.go
internal/service/resource_handler.go
internal/service/resource_pool_fetcher.go
internal/service/resource_pool_handler.go
internal/service/resource_type_handler.go
internal/testing/servers.go
internal/tool.go

This enables the code security test and addresses the violations reported by the golintci tool.

CNF-13958: Enable gosec linter configuration

---

OWNERS

/cc @rauhersu @fontivan @donpenney

CNF-13593: Update OWNERS to add midstream reviewers for Dockerfile and CSV changes

---

.containerignore
Makefile
PROJECT
api/hardwaremanagement/v1alpha1/node.go
api/hardwaremanagement/v1alpha1/node_pools.go
api/v1alpha1/orano2ims_types.go
bundle.Dockerfile
bundle/manifests/hardwaremanagement.oran.openshift.io_nodeallocationrequests.yaml
bundle/manifests/hardwaremanagement.oran.openshift.io_nodepools.yaml
bundle/manifests/hardwaremanagement.oran.openshift.io_nodereleaserequests.yaml
bundle/manifests/hardwaremanagement.oran.openshift.io_nodes.yaml
bundle/manifests/oran-o2ims.clusterserviceversion.yaml
bundle/manifests/oran.openshift.io_clusterrequests.yaml
bundle/manifests/oran.openshift.io_clustertemplates.yaml
bundle/manifests/oran.openshift.io_deploymentmanagers.yaml
bundle/manifests/oran.openshift.io_deploymentmanagertemplates.yaml
bundle/manifests/oran.openshift.io_orano2imses.yaml
bundle/metadata/annotations.yaml
config/crd/bases/hardwaremanagement.oran.openshift.io_nodepools.yaml
config/crd/bases/hardwaremanagement.oran.openshift.io_nodes.yaml
config/crd/bases/oran.openshift.io_orano2imses.yaml

CNF-14138: makefile: Fix bundle-build and catalog-build targets

---

bundle/manifests/oran-o2ims.clusterserviceversion.yaml
config/manifests/bases/oran-o2ims.clusterserviceversion.yaml

@browsell @donpenney (when available) PTL to the bundle description, as well as the proposed annotations for this operator.
/cc @rauhersu @fontivan

CNF-13591: bundle: Add infrastructure annotations for midstream builds

---

bundle/manifests/oran-o2ims.clusterserviceversion.yaml
config/manifests/bases/oran-o2ims.clusterserviceversion.yaml

Updates infrastructure annotation to notify fips compliant.
/cc @rauhersu @fontivan @donpenney

CNF-14196: bundle: Add infrastructure annotation to notify fips compliant

---

api/v1alpha1/clusterrequest_types.go
bundle/manifests/oran.openshift.io_clusterrequests.yaml
config/crd/bases/oran.openshift.io_clusterrequests.yaml
config/samples/oran.openshift.io_v1alpha1_clusterrequest.yaml

Add omitempty for ClusterRequest Timeout

---

bundle/manifests/oran-o2ims.clusterserviceversion.yaml
config/rbac/role.yaml
config/samples/oran.openshift.io_v1alpha1_clusterrequest.yaml
config/samples/oran.openshift.io_v1alpha1_clustertemplate.yaml
go.mod
go.sum
internal/controllers/clusterrequest_controller.go
internal/controllers/clusterrequest_controller_test.go
internal/controllers/utils/utils_test.go
internal/files/controllers/clusterinstance-template.yaml
vendor/github.com/stolostron/siteconfig/api/v1alpha1/clusterinstance_types.go
vendor/github.com/stolostron/siteconfig/api/v1alpha1/zz_generated.deepcopy.go
vendor/modules.txt

Align with latest from siteconfig to used extraLabels instead of clusterLabels
Also added missing permission for nodepool/status
TODO:
- ~system tests~
- ~unit tests~
- ~code cleanup~

Aligning with latest from siteconfig (using extraLabels instead of clusterLabels)

---

bundle/manifests/oran-o2ims.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controllers/clusterrequest_controller.go
internal/controllers/clusterrequest_controller_test.go
internal/controllers/utils/constants.go
internal/controllers/utils/utils.go

This update includes changes to support using the Test Plugin.

CNF-14303: Support integration with hardware manager plugin

---

docs/samples/git-setup/README.md
docs/samples/git-setup/clustertemplates/hardwaretemplates/kustomization.yaml
docs/samples/git-setup/clustertemplates/hardwaretemplates/sno-ran-du/placeholder-du-template-configmap-v1.yaml
docs/samples/git-setup/clustertemplates/kustomization.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/extra-manifest/README.md
docs/samples/git-setup/clustertemplates/version_4.Y.Z/kustomization.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/ns.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/policytemplates-defaults.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/pull-secret.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-v1.yaml
docs/samples/git-setup/policytemplates/kustomization.yaml
docs/samples/git-setup/policytemplates/version_4.Y.Z/kustomization.yaml
docs/samples/git-setup/policytemplates/version_4.Y.Z/sno-ran-du/msc-binding.yaml
docs/samples/git-setup/policytemplates/version_4.Y.Z/sno-ran-du/ns.yaml
docs/samples/git-setup/policytemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-v1.yaml
docs/samples/git-setup/policytemplates/version_4.Y.Z/source-crs/README.md

Description:
- initial GIT layout for being able to install an SNO using the O-Cloud Manager

CNF-14787: Initial GIT layout

---

internal/controllers/clustertemplate_controller.go
internal/controllers/utils/utils.go

Improves the logs created by the `ExtractSchemaRequired`, `ExtractSubSchema`, and the  `ExtractMatchingInput` functions.

Improving schema extraction logs

---

docs/cluster_configuration.md
docs/samples/git-setup/clustertemplates/version_4.Y.Z/kustomization.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v1.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v3.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/ns.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/policytemplates-defaults-v1.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/pull-secret.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-v4-Y-Z-1.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-v4-Y-Z-3.yaml
docs/samples/git-setup/policytemplates/version_4.Y.Z/kustomization.yaml
docs/samples/git-setup/policytemplates/version_4.Y.Z/sno-ran-du/msc-binding.yaml
docs/samples/git-setup/policytemplates/version_4.Y.Z/sno-ran-du/ns.yaml
docs/samples/git-setup/policytemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-pg-v4-Y-Z-v1.yaml
docs/samples/git-setup/policytemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-pg-v4-Y-Z-v2.yaml

Description:
- Add readme and examples for updating the ClusterInstance default ConfigMap.

CNF-14958: Validate change to ClusterInstance defaults ConfigMap

---

docs/cluster-configuration.md
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v2.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v3.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v4.yaml

Description:
- update an annotation instead of adding a route

CNF-14958: Update readme & examples for changing the CI defaults ConfigMap

---

bundle/manifests/oran-o2ims.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controllers/provisioningrequest_controller.go

This adds the missing RBAC role for provisioning request controller to access and modify IBGUs.

Fix RBAC role for ImageBasedUpgrade

---

bundle/manifests/oran-o2ims.clusterserviceversion.yaml
config/samples/v1alpha1_inventory.yaml

This updates the sample Inventory CR that we publish to contain the list of SMO related attributes that would typically exist in a production deployment.

Update sample inventory CR with SMO attributes

---

docs/cluster-configuration.md
docs/samples/git-setup/clustertemplates/hardwaretemplates/sno-ran-du/placeholder-du-template-configmap-v2.yaml
docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/sno-ran-du-v4-Y-Z-5.yaml

Description:
- provide readme steps for going through the update of the hardware profile used by a ProvisioningRequest

CNF-14786:  Validate switching to a new hardware profile

---

internal/service/alarms/internal/dictionary/dictionary.go
internal/service/alarms/internal/k8s_client/k8s_client.go

Add logic to fetch the rules of the hub cluster

Get rules for hub cluster

---

internal/service/alarms/internal/alertmanager/alertmanager.go
internal/service/alarms/internal/alertmanager/alertmanager.yaml
internal/service/alarms/internal/dictionary/dictionary.go
internal/service/alarms/k8s/base/endpoints.yaml
internal/service/alarms/serve.go

/cc @mlguerrero12 
/cc @alegacy

fix 'bad matcher format: Watchdog' and some post merge cleanup

---

Makefile

- removed undeploy and uninstall as its a bit too distructive (was removing other CRs that i wanted to keep)
- added additional env var for local testing
/cc @mlguerrero12 
/cc @alegacy

alarms makefile cleanup

---

bundle/manifests/oran-o2ims.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controllers/provisioningrequest_controller.go

Add kubebuilder rbac markers for hardware template CRD

Add kubebuilder rbac markers for new CRD

---

bundle/manifests/oran-o2ims.clusterserviceversion.yaml
config/manager/manager.yaml
internal/controllers/utils/constants.go

This reverts commit 7feec6eb98cbf219b032518b6b8e57f2f68f78a0.

Revert "Align postgres image var name with midstream process (#360)"

---

bundle/manifests/oran-o2ims.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controllers/inventory_controller.go
internal/controllers/utils/constants.go
internal/controllers/utils/utils.go
internal/controllers/utils/utils_test.go
internal/service/alarms/internal/alertmanager/alertmanager.go
internal/service/alarms/internal/alertmanager/alertmanager.yaml.template
internal/service/alarms/internal/alertmanager/alertmanager_test.go

CA certificate and Bearer token were missing in
alertmanager configuration

Fix alertmanager authorization failure

---

internal/service/alarms/internal/db/models/alarm_event_record.go
internal/service/alarms/internal/db/repo/alarms_repository.go
internal/service/alarms/internal/resourceserver/generated/client.gen.go
internal/service/common/db/models.go
internal/service/common/utils/repository.go
internal/service/common/utils/utils.go
internal/service/common/utils/utils_test.go
internal/service/resources/api/generated/inventory.generated.go
internal/service/resources/api/openapi.yaml
internal/service/resources/api/server.go
internal/service/resources/db/migrations/000001_baseline.up.sql
internal/service/resources/db/models/converters.go
internal/service/resources/db/models/deployment_manager.go
internal/service/resources/db/models/resource_pool.go
internal/service/resources/db/models/resource_type.go
internal/service/resources/db/models/subscription.go
internal/service/resources/db/repo/repository.go
internal/service/resources/serve.go

This adds the initial DB and API handling for the new resource server implementation.  This covers the Subscription and Deployment Manager API endpoints.  More to follow.

CNF-15750: Add DB and API handling for new resource endpoints

---

internal/service/alarms/internal/alarms_server.go
internal/service/alarms/internal/db/repo/alarms_repository.go
internal/service/alarms/internal/resourceserver/generated/client.gen.go
internal/service/common/utils/repository.go
internal/service/common/utils/utils.go
internal/service/common/utils/utils_test.go
internal/service/resources/api/generated/inventory.generated.go
internal/service/resources/api/openapi.yaml
internal/service/resources/api/server.go
internal/service/resources/db/migrations/000001_baseline.up.sql
internal/service/resources/db/models/converters.go
internal/service/resources/db/models/resource.go
internal/service/resources/db/models/resource_pool.go
internal/service/resources/db/repo/repository.go
internal/service/resources/serve.go

This adds the remaining set of API and DB models for the resource related entities.

CNF-15750: Add additional API and DB resource models

---

internal/service/resource_pool_fetcher.go
internal/service/resource_pool_handler.go

This moves certain parts of the resource pool fetcher into the handler so that it comparable to the structure/relationship between between the resource fetcher/handler.  This is to facilitate using both handlers directly from the new resource server implementation without needing to add an adaptation layer over them.

CNF-15570: Refactor pool fetcher and handler

---

bundle/manifests/oran-o2ims.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml

https://github.com/openshift-kni/oran-o2ims/issues/365

Update kube-rbac-proxy image reference

---

internal/service/common/api/filtering.go

Description:
- In the ResponseFilter from the service middleware, use url.ParseQuery() instead of Query() such that we are able to determine if an error as occurred.
- If an error happened while parsing a query, return it.
Example from the WIP artifacts server:
```
$curl -X 'GET' 'http://127.0.0.1:8000/o2ims-infrastructureArtifacts/v1/managedInfrastructureTemplates?filter=(eq,name,sno-ran-du);(eq,version,v4-17-3-1)' -H 'accept: application/json' | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   144  100   144    0     0   162k      0 --:--:-- --:--:-- --:--:--  140k
{
"detail": "failed to parse query: filter=(eq,name,sno-ran-du);(eq,version,v4-17-3-1); error: invalid semicolon separator in query", …
```

CNF-16194: Return query parsing error from filtering middleware

---

bundle/manifests/oran-o2ims.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controllers/inventory_controller.go
internal/service/alarms/api/server.go
internal/service/alarms/internal/serviceconfig/serviceconfig.go
internal/service/alarms/serve.go
internal/service/common/clients/k8s/k8s.go

- manage cronjob and a configMap from alarms server to cleanup alarm event rows
- only retention period is used to create the cleanup sql (extension TBD)

CNF-14864: cronjob to cleanup resolved alarms based on retention period

---

internal/controllers/inventory_controller.go
internal/controllers/inventory_controller_postgres.go
internal/service/alarms/internal/serviceconfig/serviceconfig.go

Adding some missing resource request values

include resource request for all apps

---

README.md

This updates the README file to add basic information about mTLS and OAuth and does some cleanup of the other sections.

Update README for mTLS and OAuth configurations

---

internal/service/alarms/api/generated/alarms.generated.go
internal/service/alarms/api/openapi.yaml

extract out alerts list for better maintainability and reusability + lint

---

internal/service/alarms/internal/db/repo/alarms_repository.go
internal/service/alarms/internal/db/repo/alarms_repository_test.go

Data model was not the correct one

Fix alarm service configuration delete resources

---

.gitignore
internal/service/alarms/internal/db/repo/alarms_repository.go
internal/service/alarms/internal/db/repo/alarms_repository_test.go
internal/service/common/utils/repository.go
internal/service/common/utils/utils.go

CNF-16538: improve test coverage for alarms - repository 

---

internal/service/resources/collector/collector_k8s.go

Currently, both the NodeCluster and DeploymentManager directly use the ManagedCluster "clusterID" label as their UUID.  This causes a conflict between the two API namespaces.  Since the NodeCluster needs the raw UUID so that we can more easily map incoming alerts to it therefore we will create a unique value for DeploymentManagers to avoid the collision.

Set unique UUID value for deployment managers

---

internal/service/alarms/api/server.go
internal/service/alarms/internal/notifier_provider/notification.go

When an alarm is Acknowledged we should send the notification right away

send AlarmAcknowledged notification immediately

---

internal/service/common/api/middleware/middleware.go

Adds details for method and status code to the request duration log.

Enhance duration logger to include more details

---

internal/controllers/provisioningrequest_controller.go
internal/controllers/provisioningrequest_controller_test.go

In the rare case where both provisioning errors (e.g., hardware provisioning, cluster installation, cluster configuration) and non-provisioning errors (e.g., validation failure due to a ProvisioningRequest update while provisioning is in progress) occur , display the error message of the already processed provisioning failure instead of the non-provisioning error message in `provisioningStatus.provisioningDetails`.

Display the provisioning failure when multiple errors occur

---

internal/controllers/utils/provision.go
internal/controllers/utils/provision_test.go
internal/controllers/utils/test_common.go

Fix the removal of required fields from ClusterInstance schema

Fix the removal of required fields from ClusterInstance schema

---

internal/service/provisioning/api/generated/provisioning.generated.go
internal/service/provisioning/api/openapi.yaml
internal/service/provisioning/api/server.go

Updates to the ProvisioningRequest REST API to align with the latest spec:
- Removed `extensions`.
- Moved input parameters into `provisioningRequestData`.
- `provisioningRequestInfo` represents the full provisioningRequest (input + output).
- Moved `provisionedResourceSets` to the top level.
- POST/PUT requests now only accept parameters defined in `provisioningRequestData`; additional parameters are not allowed.
- The response for POST/PUT requests is the entire ProvisioningRequest -`provisioningRequestInfo`.
Example responses:
POST/PUT request is rejected if status is included in the payload:
`{"detail":"request body has an error: doesn't match schema #/components/schemas/ProvisioningRequestData: property \"status\" is unsupported","status":400}`
GET response of a PR
```
{ …
```

ProvisioningRequest REST API updates

---

internal/service/common/api/middleware/middleware.go

Explicitly enable uuid format validation for request bodies in the request validator middleware instead of replying on implicit rejection during data conversion. This generates clearer error message which provides better feedback to API clients.
Example before,
`{"detail":"can't decode JSON body: invalid UUID length: 42","status":400}`
Example after,
`{"detail":"request body has an error: doesn't match schema #/components/schemas/ProvisioningRequestData: Error at \"/provisioningRequestId\": string doesn't match the format \"uuid\": invalid UUID length: 42","status":400}`

Enable UUID format validation in request middleware

---

internal/service/alarms/DEVELOPING.md

/cc @alegacy 
/cc @mlguerrero12 
/cc @bartwensley

add docs to quickly enable ACM observability for dev work

---

internal/service/alarms/DEVELOPING.md
internal/service/alarms/api/server.go
internal/service/alarms/internal/listener/pg_listener.go
internal/service/alarms/serve.go
internal/service/cluster/api/server.go
internal/service/common/api/utils.go
internal/service/common/api/utils_test.go
internal/service/common/listener/pg_listener_manager.go
internal/service/common/notifier/notifier.go
internal/service/resources/api/server.go

when a subscription is requested to be added we now perform a GET call with the appropriate auth config and expect 204 as response.
if the call goes through we can be sure that a real notification be sent out later
/cc @alegacy @mlguerrero12

CNF-16133: run reachability check before creating subscription for applicable servers

---

internal/service/common/listener/pg_listener_manager.go

during shutdown we were logging `context canceled` as a visible error. also the way it was handled is a bit awkward, this should clean it up. 
```
{"time":"2025-03-25T17:14:41.58462719Z","level":"ERROR","source":{"function":"github.com/openshift-kni/oran-o2ims/internal/service/common/listener.(*Manager).listenChannel","file":"/workspace/internal/service/common/listener/pg_listener_manager.go","line":81},
"msg":"Error listening to channel","channel":"alarm_event_record_outbox_queued",
"error":"failed to acquire connection for alarm_event_record_outbox_queued: context canceled"}
```
/cc @alegacy

remove incorrect error log during shutdown

---

internal/controllers/inventory_controller.go
internal/controllers/utils/constants.go
internal/service/alarms/internal/alertmanager/config.go
internal/service/cluster/collector/collector.go
internal/service/cluster/collector/collector_alarms.go
internal/service/cluster/db/migrations/000001_baseline.up.sql
internal/service/cluster/db/repo/repository.go
internal/service/common/db/models/alarm_definition.go

Thanos rules are collected from the default and custom config maps. The collection is added to the existing sync mechanism.

Collect Thanos rules

---

.konflux/Dockerfile.bundle
.konflux/bundle/metadata/annotations.yaml
.konflux/bundle/tests/scorecard/config.yaml
.konflux/catalog/Dockerfile.catalog
.konflux/catalog/catalog-template.yaml
.konflux/catalog/o-cloud-manager/catalog.yaml
.konflux/overlay/map_images.in.yaml
.konflux/overlay/overlay.bash
.konflux/overlay/pin_images.in.yaml

We needed a new 'annotations.yaml' with the proper configuration matching csv files. This was causing an invalid catalog when                                                                                                                                                                                                   
rendering the catalog template.                                                                                                                                                                                                                                
Full description of the problem: https://redhat-internal.slack.com/archives/C074JM28DTP/p1746193302778409 …

fix catalog ...   

---

internal/controllers/provisioningrequest_clusterconfig.go
internal/controllers/utils/hardware_utils.go

This update ensures that IMS retrieves agents from the BMH namespace if the namespace is explicitly set on the Node by the plugin. 
If no namespace is specified, it falls back to the cluster namespace to support legacy deployment scenarios.
Note: BMHs allocated to the same pool reside in the same namespace.

Retrieve agents from BMH namespace when specified

---

Makefile
bundle/manifests/oran-o2ims.clusterserviceversion.yaml
hwmgr-plugins/controller/utils/node_allocation_request.utils.go
hwmgr-plugins/loopback/cmd/start_loopbackplugin_server.go
hwmgr-plugins/loopback/controller/helpers.go
hwmgr-plugins/loopback/controller/loopback_hardwareplugin_controller.go
hwmgr-plugins/loopback/controller/nodelist_configmap.go
internal/controllers/utils/configmap.go

This PR adds the functionality to handle the creation, updation and deletion of `NodeAllocationRequest` objects for the Loopback HardwarePlugin.
/cc @browsell @alegacy @donpenney @tliu2021

Handle NodeAllocationRequest creation / updation / deletion for the Loopback HardwarePlugin

---

hwmgr-plugins/api/server/helpers.go
hwmgr-plugins/api/server/server.go
hwmgr-plugins/controller/utils/constants.go
hwmgr-plugins/loopback/controller/helpers.go
hwmgr-plugins/metal3/cmd/start_metal3plugin_server.go
hwmgr-plugins/metal3/controller/metal3_hardwareplugin_controller.go
hwmgr-plugins/metal3/server/serve.go
hwmgr-plugins/metal3/server/server.go
internal/controllers/inventory_controller.go
internal/controllers/metal3plugin_server_setup.go
internal/controllers/utils/constants.go
internal/controllers/utils/utils.go
main.go

This PR:
- Introduces the Metal3 Hardware Plugin server and controller infrastructure to `hwmgr-plugins`.
- Refactors the Loopback Hardware Plugin server by defining a common `HardwarePluginServer` that implements the provisioning OpenAPI spec.
ℹ️ Subsequent PR(s) will incorporate the `NodeAllocationRequest` handling for the Metal3 Hardware Plugin server.
/cc @browsell @alegacy @donpenney @tliu2021

Add metal3 hardware plugin server and controller infrastructure

---

api/hardwaremanagement/v1alpha1/node_allocation_requests.go
bundle/manifests/o2ims-hardwaremanagement.oran.openshift.io_nodeallocationrequests.yaml
bundle/manifests/oran-o2ims.clusterserviceversion.yaml
config/crd/bases/o2ims-hardwaremanagement.oran.openshift.io_nodeallocationrequests.yaml
config/manifests/bases/oran-o2ims.clusterserviceversion.yaml
config/samples/v1alpha1_nodeallocationrequest.yaml
hwmgr-plugins/api/client/provisioning/generated.go
hwmgr-plugins/api/openapi/specs/provisioning.yaml
hwmgr-plugins/api/server/provisioning/generated.go
hwmgr-plugins/api/server/provisioning/helpers.go
hwmgr-plugins/api/server/provisioning/server.go
hwmgr-plugins/controller/utils/node_allocation_request.go
hwmgr-plugins/loopback/controller/helpers.go
hwmgr-plugins/loopback/controller/loopback_hardwareplugin_controller.go
hwmgr-plugins/loopback/controller/nodelist_configmap.go
hwmgr-plugins/metal3/controller/helpers.go
hwmgr-plugins/metal3/controller/metal3_nodeallocationrequest_controller.go
internal/controllers/provisioningrequest_hwprovision.go
vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/node_allocation_requests.go

This update adds a configTransactionId to the NodeAllocationRequest in order to validate that the condtions being returned by a plugin query are for the most recent transaction.
This update also adds the clusterId to the NAR.

Update day2 config interactions with plugin

---

hwmgr-plugins/metal3/controller/helpers.go
hwmgr-plugins/metal3/controller/metal3_nodeallocationrequest_controller.go

Fix race condition where `NodeAllocationRequest` completed prematurely before `PreprovisioningImage` network data clearing finished. Refactor progress checking to always validate processing status and implement proper requeue handling.
/cc @donpenney @browsell

Resolve NodeAllocationRequest race condition in network data clearing

---

OWNERS_ALIASES

Add Sharat Akhoury to owners

---

.tekton/o-cloud-manager-4-20-pull-request.yaml
.tekton/o-cloud-manager-4-20-push.yaml
.tekton/o-cloud-manager-bundle-4-20-pull-request.yaml
.tekton/o-cloud-manager-bundle-4-20-push.yaml
.tekton/o-cloud-manager-fbc-4-20-pull-request.yaml
.tekton/o-cloud-manager-fbc-4-20-push.yaml

- Without this, changes to the library could be breaking and merge without warning
- See: https://github.com/openshift-kni/oran-o2ims/pull/846 & https://github.com/openshift-kni/oran-o2ims/pull/853

Update on-cel-expression to include telco5g-konflux in all components

---

internal/controllers/provisioningrequest_controller.go
internal/controllers/provisioningrequest_controller_test.go

Refactor the HardwarePlugin client initialization logic in the ProvisioningRequest reconciler:
- correctly initialize the HardwarePlugin client before calling `handlePreProvisioning`
- add retry with delay mechanism 
ℹ️ Assisted-by: Cursor and claude-4-sonnet
/cc @donpenney @browsell

CNF-19057: Refactor HardwarePlugin client initialization

---

.konflux/catalog/fbc-images-resolvable-integration-test-idms.yaml
.tekton/images-mirror-set.yaml

- According to docs it should be `config.openshift.io/v1` (https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/config_apis/imagedigestmirrorset-config-openshift-io-v1)

Fix the apiVersion for IDMS files

---

api/hardwaremanagement/plugins/v1alpha1/node_allocation_requests.go
api/hardwaremanagement/v1alpha1/hardwaretemplate_types.go
api/provisioning/v1alpha1/clustertemplate_types.go
api/provisioning/v1alpha1/provisioningrequest_types.go
bundle/manifests/clcm.openshift.io_clustertemplates.yaml
bundle/manifests/clcm.openshift.io_hardwaretemplates.yaml
bundle/manifests/clcm.openshift.io_provisioningrequests.yaml
bundle/manifests/plugins.clcm.openshift.io_nodeallocationrequests.yaml
config/crd/bases/clcm.openshift.io_clustertemplates.yaml
config/crd/bases/clcm.openshift.io_hardwaretemplates.yaml
config/crd/bases/clcm.openshift.io_provisioningrequests.yaml
config/crd/bases/plugins.clcm.openshift.io_nodeallocationrequests.yaml
docs/cluster-provisioning.md
vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/plugins/v1alpha1/node_allocation_requests.go
vendor/github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1/hardwaretemplate_types.go
vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/clustertemplate_types.go
vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_types.go

Remove oran from crd shortnames
Generated-By: Cursor/claude-4-sonnet

Remove oran from crd shortnames

---

Makefile

Some additional updates to improve the robustness of the makefile

Makefile robustness updates

---

.tekton/build-pipeline.yaml

Reverts openshift-kni/oran-o2ims#970
cc. @donpenney

Revert "chore(deps): update quay.io/konflux-ci/konflux-vanguard/task-rpms-signature-scan:0.2 docker digest to 232bd31"

---

Makefile

The golangci-lint tool was being executed every time docker-build is run due to recent updates to the deps-update target. This update separates the golangci-lint target into a run target and a download target, updating the deps-update dependency to golangci-lint-download. This ensures the linter isn't unintentionally run when building the docker image.
This update also makes similar changes to the other tool targets, for consistency.
Assisted-by: Claude Code/claude-sonnet-4

Update Makefile to separate downloading and running tools

---

internal/controllers/provisioningrequest_controller.go

This PR removes conditional cluster resource creation based on hardware provisioning mode. Resources are now created consistently in the pre-provisioning phase for all scenarios.
Addresses: [OCPBUGS-61998](https://issues.redhat.com/browse/OCPBUGS-61998)
/cc @browsell @Missxiaoguo @irinamihai

OCPBUGS-61998: Consolidate cluster resource creation into pre-provisioning phase

---

api/hardwaremanagement/v1alpha1/hardwareprofile_types.go
bundle/manifests/clcm.openshift.io_hardwareprofiles.yaml
bundle/manifests/oran-o2ims.clusterserviceversion.yaml
config/crd/bases/clcm.openshift.io_hardwareprofiles.yaml
config/manifests/bases/oran-o2ims.clusterserviceversion.yaml

- Add XValidation rule to prevent spec changes after validation
- Align resource association with actual CRD functionality

Fix HardwareProfile CRD resource association and add validation
